export type CurriculumProject = {
  id: string;
  nombre: string;
  nombreJa: string;
  definicion: string;
  formato: string;
  evalTipo: "interaccion" | "produccion";
  evalNota: string;
  evalDimensiones: string[];
  competencias: string[];
  checklist: string[];
};

export type CurriculumModule = {
  id: string;
  numero: number;
  nombre: string;
  nombreJa: string;
  nivel: 1 | 2 | 3;
  cefr: "A1" | "A2" | "B1";
  jlpt: "N5" | "N4" | "N3";
  lecciones: number[];
  canDo: string;
  vocabTemas: string[];
  competencias: string[];
  criteriosAvance: string[];
  proyectos: CurriculumProject[];
};

export const CURRICULUM_MODULES: CurriculumModule[] = [
  {
    id: "g1-a",
    numero: 1,
    nombre: "Primeras palabras",
    nombreJa: "はじめのことば",
    nivel: 1,
    cefr: "A1",
    jlpt: "N5",
    lecciones: [1, 2, 3],
    canDo: "Puedes presentarte, hablar de tu rutina diaria, decir a qué hora haces las cosas, describir dónde están personas y objetos, e invitar a alguien a hacer algo.",
    vocabTemas: [
      "números y precios",
      "días y horas",
      "objetos cotidianos y de clase",
      "nacionalidades y profesiones",
      "lugares de la ciudad",
      "familia y amigos cercanos",
    ],
    competencias: [
      "presentación personal",
      "rutina diaria",
      "tiempo y lugar",
      "demostrativos",
      "ubicación",
      "objetos cotidianos",
      "invitaciones",
      "horarios",
      "interacción básica",
    ],
    criteriosAvance: [
      "Se presenta en japonés completo sin leer un guión (nombre, origen, ocupación)",
      "Describe dónde está algo o alguien usando ある/いる correctamente",
      "Habla de su rutina usando al menos 5 verbos distintos con hora y día",
      "Hace y responde invitaciones con ませんか sin que se le recuerde la estructura",
    ],
    proyectos: [
      {
        id: "g1-a-p1",
        nombre: "Mini entrevista de presentación",
        nombreJa: "はじめまして面談",
        definicion: "El alumno y el profesor o un compañero hacen una entrevista de presentación en japonés de 3–4 minutos. Sin guión. El entrevistador hace preguntas variadas: nombre, origen, ocupación, gustos, rutina.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["presentación personal", "interacción básica", "horarios"],
        checklist: [
          "Sostiene la entrevista sin recurrir al español",
          "Responde a todas las preguntas (nombre, origen, ocupación, gustos)",
          "Hace al menos 2 preguntas propias de vuelta",
          "Reacciona a las respuestas (へえ、そうですか、いいですね…)",
        ],
      },
      {
        id: "g1-a-p2",
        nombre: "Mi día simple",
        nombreJa: "わたしの一日",
        definicion: "El alumno describe su día típico en japonés: a qué hora hace qué, dónde, y con quién. Puede usar fotos o solo voz. Máximo 2 minutos.",
        formato: "video",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["rutina diaria", "tiempo y lugar", "ubicación"],
        checklist: [
          "タスク遂行 · Incluye al menos 6 actividades con hora y lugar",
          "タスク遂行 · Describe dónde está algo o alguien con ある・いる",
          "正確さ · Las partículas に・で・を・が están bien usadas",
          "流暢さ · El video fluye sin pausas largas ni lectura palabra por palabra",
        ],
      },
    ],
  },
  {
    id: "g1-b",
    numero: 2,
    nombre: "En acción",
    nombreJa: "こうどうしよう",
    nivel: 1,
    cefr: "A1",
    jlpt: "N5",
    lecciones: [4, 5, 6],
    canDo: "Puedes describir personas y cosas con adjetivos, expresar lo que te gusta o no, conectar acciones con la forma て, pedir favores, dar permiso, y explicar lo que está pasando en este momento.",
    vocabTemas: [
      "adjetivos de tamaño, color, forma y personalidad",
      "pasatiempos y deportes",
      "comida y bebida",
      "verbos de acción cotidiana",
      "reglas del hogar y la escuela",
    ],
    competencias: [
      "forma て",
      "permisos",
      "prohibiciones",
      "peticiones",
      "adjetivos",
      "gustos",
      "razones",
      "descripción",
      "secuencia de acciones",
      "movimiento con propósito",
    ],
    criteriosAvance: [
      "Describe 3 cosas distintas usando adjetivos い y な sin confundir la conjugación",
      "Encadena al menos 3 acciones con forma て sin pausas largas",
      "Distingue てください / てもいい / てはいけません en contexto sin que se le indique cuál usar",
      "Describe lo que alguien está haciendo ahora mismo usando ている de forma espontánea",
    ],
    proyectos: [
      {
        id: "g1-b-p1",
        nombre: "Club de recomendaciones",
        nombreJa: "おすすめ会",
        definicion: "Cada alumno recomienda algo (comida, lugar, actividad, serie) usando adjetivos y gustos. Los demás reaccionan y preguntan. 2 minutos de presentación + preguntas.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["adjetivos", "gustos y preferencias", "descripción"],
        checklist: [
          "タスク遂行 · Recomienda algo con al menos 3 adjetivos distintos",
          "タスク遂行 · Explica por qué lo recomienda (gustos / razones con から)",
          "正確さ · Conjuga adjetivos い y な correctamente",
          "流暢さ · Presenta con ritmo natural y responde preguntas",
        ],
      },
      {
        id: "g1-b-p2",
        nombre: "Reglas de un lugar",
        nombreJa: "この場所のルール",
        definicion: "El alumno inventa o describe las reglas de un lugar real o ficticio (casa, clase, trabajo, nave espacial…) usando forma て. Puede ser serio o gracioso.",
        formato: "presentación Zoom o video",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["forma て", "reglas y permisos", "descripción de acciones"],
        checklist: [
          "タスク遂行 · Presenta al menos 4 reglas coherentes con el lugar",
          "タスク遂行 · Mezcla permisos (てもいい) y prohibiciones (てはいけません)",
          "正確さ · La forma て está bien formada",
          "流暢さ · Las reglas se presentan con fluidez, no leídas",
        ],
      },
      {
        id: "g1-b-p3",
        nombre: "¿Qué está haciendo?",
        nombreJa: "今、何してる？",
        definicion: "El profesor comparte en pantalla una foto o escena (anime, cotidiana, divertida). Los 5 alumnos describen en japonés qué están haciendo las personas, qué hay en la escena, y se hacen preguntas entre sí. 4–5 min en grupo.",
        formato: "conversación Zoom con pantalla compartida",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["ている", "adjetivos descriptivos", "descripción de escenas"],
        checklist: [
          "Describe al menos 3 personas o cosas con ている",
          "Hace al menos 1 pregunta a un compañero sobre la escena",
          "Responde a las preguntas del grupo",
          "Mantiene el intercambio en japonés",
        ],
      },
    ],
  },
  {
    id: "g1-c",
    numero: 3,
    nombre: "Tu voz",
    nombreJa: "じぶんのこえ",
    nivel: 1,
    cefr: "A1",
    jlpt: "N5",
    lecciones: [7, 8, 9],
    canDo: "Puedes hablar de tu familia y personas cercanas, dar tu opinión sobre temas cotidianos, reportar lo que alguien dijo, y describir cosas, lugares o personas usando oraciones completas como modificadores.",
    vocabTemas: [
      "familia y relaciones",
      "medios de comunicación (películas, música, libros)",
      "restaurantes y lugares de ocio",
      "estados de ánimo y preferencias",
    ],
    competencias: [
      "opinión",
      "citas",
      "modificación de sustantivo",
      "descripción de personas",
      "acciones habituales",
      "modificadores",
      "opinión escrita",
      "interacción",
      "formas cortas/largas",
    ],
    criteriosAvance: [
      "Usa al menos 2 cláusulas de modificación de sustantivo sin preparación previa",
      "Expresa y defiende una opinión con と思います cuando se le cuestiona",
      "Reporta lo que otra persona dijo usando と言っていました en conversación real",
      "Alterna entre formas largas y cortas apropiadamente según el contexto",
    ],
    proyectos: [
      {
        id: "g1-c-p1",
        nombre: "Reseña y reacción",
        nombreJa: "レビュー会",
        definicion: "El alumno reseña algo (película, libro, canción, lugar) usando modificación de sustantivo y opiniones. Los compañeros reaccionan y debaten. 3 minutos + preguntas.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["modificación de sustantivo", "opiniones", "citas indirectas"],
        checklist: [
          "タスク遂行 · Reseña con al menos 2 cláusulas de modificación de sustantivo",
          "タスク遂行 · Da opinión propia (と思います) y responde 1 pregunta",
          "正確さ · Las cláusulas de modificación están bien construidas",
          "流暢さ · La reseña fluye sin lectura palabra por palabra",
        ],
      },
      {
        id: "g1-c-p2",
        nombre: "Persona o personaje importante",
        nombreJa: "大切な人・キャラ紹介",
        definicion: "El alumno presenta a alguien real o ficticio: lo describe con cláusulas de modificación, da su opinión, y cuenta algo que esa persona dijo. 2–3 minutos.",
        formato: "presentación Zoom o video",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["modificación de sustantivo", "descripción de personas", "formas cortas"],
        checklist: [
          "タスク遂行 · Describe a la persona con al menos 3 cláusulas de modificación",
          "タスク遂行 · Incluye algo que esa persona dijo (と言っていました) y da su opinión",
          "正確さ · Formas cortas y modificación bien usadas",
          "流暢さ · Habla con conexión real al tema y ritmo natural",
        ],
      },
      {
        id: "g1-c-p3",
        nombre: "Lo que descubrí",
        nombreJa: "私が見つけたもの",
        definicion: "El alumno presenta algo que descubrió recientemente (app, receta, dato curioso, lugar, canción) usando modificación de sustantivo para describirlo, menciona qué alguien dijo sobre ello, y da su propia opinión. 2–3 min. Los compañeros reaccionan.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["modificación de sustantivo", "と言っていました", "と思います"],
        checklist: [
          "タスク遂行 · Describe el descubrimiento con al menos 1 cláusula de modificación de sustantivo",
          "タスク遂行 · Incluye algo que alguien dijo (と言っていました) y da su propia opinión (と思います)",
          "正確さ · La cláusula de modificación está bien construida",
          "流暢さ · La presentación fluye y no se lee palabra por palabra",
        ],
      },
    ],
  },
  {
    id: "g1-d",
    numero: 4,
    nombre: "Miras hacia adelante",
    nombreJa: "これからのこと",
    nivel: 1,
    cefr: "A1",
    jlpt: "N5",
    lecciones: [10, 11, 12],
    canDo: "Puedes comparar opciones y explicar cuál prefieres y por qué, hablar de planes e intenciones, contar experiencias pasadas, dar consejos, y expresar obligaciones o lo que alguien debería hacer.",
    vocabTemas: [
      "viajes y turismo",
      "planes de vida y metas",
      "salud y bienestar",
      "situaciones cotidianas que requieren consejo",
      "experiencias nuevas y bucket list",
    ],
    competencias: [
      "comparaciones",
      "planes",
      "experiencias",
      "deseos",
      "consejos",
      "obligación",
      "explicación con んです",
      "pasado",
      "comparación",
      "cambio personal",
    ],
    criteriosAvance: [
      "Compara dos opciones usando より / いちばん con razones concretas sin titubear",
      "Habla de planes usando つもり y de deseos usando たい sin confundirlos",
      "Cuenta algo que nunca ha hecho pero quiere hacer usando ことがある",
      "Da un consejo completo usando ほうがいい y explica la razón con んです",
    ],
    proyectos: [
      {
        id: "g1-d-p1",
        nombre: "Plan soñado",
        nombreJa: "夢のプラン",
        definicion: "El alumno planea un viaje, proyecto de vida o meta: compara opciones, habla de lo que quiere hacer, de sus experiencias previas, y da recomendaciones. 4–5 minutos.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["comparaciones", "planes e intenciones", "experiencias", "recomendaciones"],
        checklist: [
          "タスク遂行 · Compara 2 opciones y explica una intención (つもり)",
          "タスク遂行 · Menciona una experiencia (ことがある) y un consejo (ほうがいい)",
          "正確さ · Comparativos y つもり bien formados",
          "流暢さ · La presentación fluye y se sostiene 4–5 minutos",
        ],
      },
      {
        id: "g1-d-p2",
        nombre: "Consultorio de consejos",
        nombreJa: "お悩み相談室",
        definicion: "Un alumno presenta un problema (real o inventado) y los demás dan consejos usando ほうがいい, なければなりません y んです. Rotar roles. 5–6 minutos.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["consejos", "obligaciones", "explicaciones con んです"],
        checklist: [
          "Da consejos comprensibles al problema planteado",
          "Reacciona a los consejos de los demás",
          "Pregunta por más detalles cuando hace falta",
          "Mantiene el intercambio activo en grupo, en japonés",
        ],
      },
      {
        id: "g1-d-p3",
        nombre: "Mi lista de vida",
        nombreJa: "バケットリスト",
        definicion: "El alumno presenta su bucket list personal: cosas que ya hizo (ことがある), cosas que nunca ha hecho pero quiere hacer (たい), y qué necesita hacer para lograrlo (なければなりません). 3–4 min. El grupo pregunta y comparte también.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["ことがある", "たい", "なければなりません", "んです"],
        checklist: [
          "タスク遂行 · Menciona al menos 3 experiencias pasadas con ことがある (o ことがない)",
          "タスク遂行 · Presenta al menos 2 metas futuras con razón (たい・んです)",
          "正確さ · ことがある y たい bien formados y diferenciados",
          "流暢さ · La presentación fluye y se siente personal, no memorizada",
        ],
      },
    ],
  },
  {
    id: "g2-a",
    numero: 5,
    nombre: "Posibilidades",
    nombreJa: "できること",
    nivel: 2,
    cefr: "A2",
    jlpt: "N4",
    lecciones: [13, 14, 15],
    canDo: "Puedes hablar de lo que eres capaz de hacer, dar múltiples razones, manejar intercambios de dar y recibir favores de forma natural, y expresar intenciones y preparativos para el futuro.",
    vocabTemas: [
      "habilidades y talentos",
      "regalos y favores sociales",
      "planes y preparativos",
      "peticiones formales y cotidianas",
      "verbos de movimiento con propósito",
    ],
    competencias: [
      "volicional",
      "preparación",
      "peticiones formales",
      "potencial",
      "てみる",
      "razones múltiples",
      "あげる/くれる/もらう",
      "favores",
      "gratitud",
    ],
    criteriosAvance: [
      "Usa verbos en forma potencial de forma fluida, incluyendo irregulares",
      "Da múltiples razones con し...し sin necesitar que se le recuerde la estructura",
      "Maneja あげる/くれる/もらう correctamente según la dirección del intercambio",
      "Distingue ておく (preparación anticipada) de てみる (probar algo nuevo) en contexto",
    ],
    proyectos: [
      {
        id: "g2-a-p1",
        nombre: "Organicemos algo",
        nombreJa: "みんなで企画しよう",
        definicion: "En grupo, planear un evento real o ficticio: cada alumno propone, acepta responsabilidades, prepara algo con ておく, y hace peticiones formales. Los 5 trabajan juntos hacia un plan concreto. 6–8 min.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["dar/recibir favores", "intenciones", "peticiones formales", "preparación anticipada"],
        checklist: [
          "Contribuye con al menos una propuesta al plan del grupo",
          "Hace o responde una petición dentro de la conversación",
          "Reacciona y construye sobre lo que dicen los demás",
          "El grupo llega a un plan concreto",
        ],
      },
      {
        id: "g2-a-p2",
        nombre: "La primera vez",
        nombreJa: "はじめての〇〇",
        definicion: "Cada alumno cuenta algo que hizo por primera vez recientemente (real o imaginario) usando てみた, explica con し cómo fue, y comenta si lo recomendaría. El grupo pregunta y comparte sus propias experiencias. 5–6 min en grupo.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["てみる", "し (razones múltiples)", "そうだ (apariencia)", "recomendaciones"],
        checklist: [
          "Cuenta la experiencia usando てみた de forma correcta",
          "Da al menos 2 razones con し sobre cómo fue",
          "Responde preguntas del grupo sobre su experiencia",
          "Recomienda o no recomienda con razones comprensibles",
        ],
      },
    ],
  },
  {
    id: "g2-b",
    numero: 6,
    nombre: "Si y cuando",
    nombreJa: "もしもの話",
    nivel: 2,
    cefr: "A2",
    jlpt: "N4",
    lecciones: [16, 17, 18],
    canDo: "Puedes plantear condiciones e hipótesis, transmitir información de segunda mano, narrar eventos en secuencia con matices, y expresar arrepentimiento o resultados inesperados.",
    vocabTemas: [
      "noticias y rumores",
      "estados emocionales",
      "situaciones hipotéticas",
      "verbos transitivos e intransitivos",
      "expresiones de resultado y consecuencia",
    ],
    competencias: [
      "condicionales",
      "hearsay",
      "consecuencias",
      "arrepentimiento",
      "ばよかった",
      "hipótesis",
      "ながら",
      "transitivo/intransitivo",
      "emociones",
    ],
    criteriosAvance: [
      "Usa たら, と y ば para tipos de condición distintos sin mezclarlos arbitrariamente",
      "Reporta información de segunda mano con そうだ (伝聞) de forma espontánea",
      "Expresa arrepentimiento con ばよかった en un contexto real, no forzado",
      "Distingue verbos transitivos e intransitivos y los usa correctamente en contexto",
    ],
    proyectos: [
      {
        id: "g2-b-p1",
        nombre: "Si pudiera volver",
        nombreJa: "もし戻れたら",
        definicion: "Cada alumno comparte algo que haría diferente si pudiera volver atrás (real o ficticio), usando ばよかった y condicionales. El grupo reacciona y hace preguntas. 5–6 min.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["arrepentimiento", "hipótesis", "condicionales"],
        checklist: [
          "Plantea una situación pasada comprensible",
          "Expresa qué cambiaría y por qué",
          "Responde a las reacciones del grupo",
          "Sostiene la reflexión en japonés",
        ],
      },
      {
        id: "g2-b-p2",
        nombre: "¿Y si...?",
        nombreJa: "もしも〇〇だったら",
        definicion: "Conversación grupal sobre situaciones hipotéticas divertidas o reveladoras: si ganaras la lotería, si fueras invisible, si pudieras vivir en Japón. Cada alumno propone un escenario, el grupo reacciona y debate. 5–6 min.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["たら/ば (hipótesis)", "と (consecuencia natural)", "ために (propósito)"],
        checklist: [
          "Plantea su hipotético con claridad usando たら o ば",
          "Responde al hipotético de al menos otro compañero",
          "El intercambio tiene ida y vuelta real entre los 5",
          "Mantiene el japonés durante toda la conversación",
        ],
      },
    ],
  },
  {
    id: "g2-c",
    numero: 7,
    nombre: "Con conciencia",
    nombreJa: "ていねいに話す",
    nivel: 2,
    cefr: "A2",
    jlpt: "N4",
    lecciones: [19, 20, 21],
    canDo: "Puedes ajustar tu nivel de formalidad según el contexto, agradecer y pedir de forma apropiada en situaciones formales, describir cambios graduales, y hablar de situaciones donde algo te pasa o haces que alguien haga algo.",
    vocabTemas: [
      "lenguaje de trabajo y situaciones formales",
      "agradecimientos y cortesía avanzada",
      "cambios y evoluciones personales",
      "problemas sociales y relaciones de poder",
    ],
    competencias: [
      "keigo",
      "humildad",
      "registro formal",
      "ようになる",
      "ようにする",
      "definiciones",
      "pasiva",
      "てほしい",
      "argumentación",
    ],
    criteriosAvance: [
      "Usa al menos 3 formas honoríficas y 2 humildes correctamente en un contexto simulado",
      "Describe cambios graduales con ようになる y ようにする sin que se le indique",
      "Usa la voz pasiva espontáneamente para describir lo que le pasó a alguien",
      "Expresa lo que quiere que otros hagan con てほしい distinguiéndolo de たい",
    ],
    proyectos: [
      {
        id: "g2-c-p1",
        nombre: "Cómo he cambiado",
        nombreJa: "変わったこと",
        definicion: "Cada alumno reflexiona en grupo sobre cómo ha cambiado desde que empezó japonés: qué puede hacer ahora que antes no podía, qué quiere mejorar. El grupo pregunta y comparte también. 6–8 min.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["ようになる", "ようにする", "reflexión personal", "voz pasiva"],
        checklist: [
          "Comunica al menos 2 cambios personales de forma comprensible",
          "Responde preguntas del grupo sobre sus cambios",
          "Sostiene la conversación con ida y vuelta",
          "Mantiene el intercambio en japonés",
        ],
      },
      {
        id: "g2-c-p2",
        nombre: "El noticiero",
        nombreJa: "ニュースキャスター",
        definicion: "Cada alumno presenta una noticia breve (real, inventada o absurda) en estilo formal de noticiero japonés. Usa voz pasiva, はずだ y という de forma natural. Los demás reaccionan con preguntas al final. 2–3 min por alumno.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["voz pasiva", "はずだ", "という", "registro formal"],
        checklist: [
          "タスク遂行 · Mantiene el registro formal durante toda la presentación",
          "タスク遂行 · Usa voz pasiva al menos 2 veces",
          "正確さ · La voz pasiva está bien formada",
          "流暢さ · El tono es de noticiero, no de conversación casual",
        ],
      },
    ],
  },
  {
    id: "g2-d",
    numero: 8,
    nombre: "La línea de llegada",
    nombreJa: "ゴールへ",
    nivel: 2,
    cefr: "A2",
    jlpt: "N4",
    lecciones: [22, 23],
    canDo: "Puedes hacer que otros hagan cosas, expresar concesiones y matices complejos, tomar decisiones y explicar tus reglas personales, y sostener una conversación en japonés sobre un tema que te importa.",
    vocabTemas: [
      "decisiones de vida y valores personales",
      "dinámicas de grupo y responsabilidad",
      "expresiones de fluidez conversacional",
      "vocabulario personal y de identidad",
    ],
    competencias: [
      "fluidez",
      "síntesis",
      "respuesta espontánea",
      "decisiones",
      "concesión",
      "matices",
      "causativa",
      "causativa-pasiva",
      "responsabilidad",
    ],
    criteriosAvance: [
      "Usa la causativa para hacer que alguien haga algo (autoridad, permiso, petición) con naturalidad",
      "Usa のに para expresar frustración o contraste sin que se le sugiera la estructura",
      "Sostiene una conversación de 5+ minutos sobre un tema elegido por él sin recurrir al español",
      "Responde preguntas inesperadas del grupo o del profesor sin pausas largas",
    ],
    proyectos: [
      {
        id: "g2-d-p1",
        nombre: "Presentación final conversacional",
        nombreJa: "卒業トーク",
        definicion: "Presentación de 6–8 minutos sobre cualquier tema que le importe al alumno. Sin guión. El grupo hace preguntas al final. Marca el cierre del ciclo completo.",
        formato: "presentación Zoom con preguntas",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["fluidez conversacional", "variedad de estructuras", "respuesta espontánea"],
        checklist: [
          "タスク遂行 · Sostiene 6–8 min sobre un tema propio sin cambiar al español",
          "タスク遂行 · Responde preguntas inesperadas del grupo",
          "正確さ · Usa una variedad de estructuras bien formadas",
          "流暢さ · El ritmo es natural y la presentación se siente propia",
        ],
      },
      {
        id: "g2-d-p2",
        nombre: "Mis reglas de vida",
        nombreJa: "私のルール",
        definicion: "El alumno presenta su filosofía personal: qué ha decidido hacer (ことにする), qué se obliga a sí mismo a hacer (causativa reflexiva), para cuándo (までに), y qué le frustra que aún no pasa (のに). 3–4 min. El grupo pregunta.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["ことにする", "causativa", "のに", "までに"],
        checklist: [
          "タスク遂行 · Presenta al menos 2 reglas personales concretas con ことにする",
          "タスク遂行 · Usa のに para contrastar con la realidad",
          "正確さ · ことにする y causativa bien formados",
          "流暢さ · El tono es genuino y personal, no memorizado",
        ],
      },
    ],
  },
  {
    id: "cj-a",
    numero: 9,
    nombre: "Opiniones con matiz",
    nombreJa: "意見のニュアンス",
    nivel: 3,
    cefr: "B1",
    jlpt: "N3",
    lecciones: [],
    canDo: "Puedes dar tu opinión y defenderla con matices, describir semejanzas y patrones con ようなN, explicar causas con ～のは〜からだ, y distinguir verbos transitivos e intransitivos en contexto real.",
    vocabTemas: [
      "comida y cultura de consumo",
      "desastres naturales y emergencias",
      "infancia y nostalgia",
      "cambios generacionales",
    ],
    competencias: [
      "opinión con matiz",
      "comparación sofisticada",
      "causa y consecuencia",
      "transitivos e intransitivos",
      "patrones generacionales",
      "debate",
      "descripción avanzada",
    ],
    criteriosAvance: [
      "Usa N₁といえば de forma espontánea para introducir o cambiar un tema",
      "Distingue verbos transitivos e intransitivos en contexto real sin preparación previa",
      "Expresa causas y razones con ～のは〜からだ de forma natural",
      "Construye comparaciones usando V〔普通形〕ようなN en oraciones complejas sin apoyo",
    ],
    proyectos: [
      {
        id: "cj-a-p1",
        nombre: "Reporte generacional",
        nombreJa: "世代ギャップレポート",
        definicion: "El alumno hace un video de 3 minutos comparando cómo son los jóvenes de hoy con cómo eran las cosas en su infancia: qué querían, qué hacían siempre, y qué patrones identifica en su generación.",
        formato: "video",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["comparación generacional", "ようなN", "Nばかり", "ついVしまう"],
        checklist: [
          "タスク遂行 · Compara al menos 2 aspectos de hoy vs. la infancia propia",
          "タスク遂行 · Usa ようなN o ようだ al describir un patrón o semejanza",
          "正確さ · ついしまう y ばかり bien formados",
          "流暢さ · El video fluye sin lectura palabra por palabra",
        ],
      },
      {
        id: "cj-a-p2",
        nombre: "Debate de posturas",
        nombreJa: "どっちが大事？",
        definicion: "Conversación grupal sobre un tema controversial (comida, emergencias, valores sociales): cada alumno plantea su postura usando のでしょうか para abrir debate y la defiende con ～のは〜だ y ～のは〜からだ. 5–6 minutos.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["のでしょうか", "のは〜だ", "のは〜からだ", "debate de posturas"],
        checklist: [
          "Plantea su postura con claridad y la sostiene ante preguntas",
          "Usa のでしょうか para introducir reflexión o pregunta al grupo",
          "Responde al argumento de al menos un compañero",
          "Mantiene el intercambio en japonés durante toda la conversación",
        ],
      },
    ],
  },
  {
    id: "cj-b",
    numero: 10,
    nombre: "Datos y tendencias",
    nombreJa: "データと傾向",
    nivel: 3,
    cefr: "B1",
    jlpt: "N3",
    lecciones: [],
    canDo: "Puedes interpretar y presentar datos de encuestas o gráficas, conectar ideas en cadena con 連用中止, hacer comparaciones sofisticadas con ほど, y construir párrafos coherentes en japonés hablado y escrito.",
    vocabTemas: [
      "estadísticas y encuestas",
      "imágenes y estereotipos culturales",
      "salud y hábitos de sueño",
      "comparaciones entre países",
    ],
    competencias: [
      "interpretación de datos",
      "presentación de encuestas",
      "連用中止",
      "comparaciones con ほど",
      "generalización y reportativo",
      "construcción de párrafos",
      "comparación cultural",
    ],
    criteriosAvance: [
      "Presenta datos de una tabla o gráfica usando 〔表/グラフ〕で見ると con fluidez",
      "Usa 連用中止 para conectar 2 o más cláusulas sin pausa ni partícula de unión",
      "Distingue ものだ (generalización/recuerdo) de ということだ (reportativo) en contexto",
      "Construye oraciones largas y coherentes sin perder el hilo gramatical",
    ],
    proyectos: [
      {
        id: "cj-b-p1",
        nombre: "Presentación de mini-encuesta",
        nombreJa: "ミニアンケート発表",
        definicion: "El alumno encuesta a 3–5 personas fuera de clase (familia, amigos, redes) y luego presenta los resultados usando 〔グラフ〕で見ると〜ことがわかる, 連用中止 y ということだ. 3–4 minutos.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["グラフで見ると", "連用中止", "ということだ", "presentación de datos"],
        checklist: [
          "タスク遂行 · Presenta al menos 2 resultados de la encuesta con datos concretos",
          "タスク遂行 · Usa グラフ/表で見ると o ということだ al menos una vez",
          "正確さ · 連用中止 y estructuras de datos bien formadas",
          "流暢さ · La presentación fluye sin lectura y tiene ritmo de informe",
        ],
      },
      {
        id: "cj-b-p2",
        nombre: "Japón vs. mi país",
        nombreJa: "日本 vs. 私の国",
        definicion: "Conversación grupal comparando Japón con los países de los alumnos: imágenes, hábitos, costumbres. Cada alumno aporta datos o ejemplos usando XはYほど〜ない, Vテいく/きた y ものだ. 5–6 minutos.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["XはYほど〜ない", "Vテいく/きた", "ものだ", "comparación cultural"],
        checklist: [
          "Aporta al menos 1 comparación concreta con XはYほど〜ない",
          "Usa Vテいく o Vテきた para describir una tendencia",
          "Responde a las comparaciones de al menos un compañero",
          "Mantiene el intercambio en japonés durante toda la conversación",
        ],
      },
    ],
  },
  {
    id: "cj-c",
    numero: 11,
    nombre: "Causa, contraste y cultura",
    nombreJa: "原因・対比・文化",
    nivel: 3,
    cefr: "B1",
    jlpt: "N3",
    lecciones: [],
    canDo: "Puedes hablar de causas y propósitos con ため, condicionar tu argumento con なら, expresar matices con わけではない y といっても, y discutir diferencias culturales con vocabulario preciso.",
    vocabTemas: [
      "inventos y tecnología",
      "medioambiente y reciclaje",
      "gestos y comunicación no verbal",
      "malentendidos culturales",
    ],
    competencias: [
      "causa y propósito",
      "condición contextual",
      "matices y contraste",
      "comparación avanzada",
      "pasado habitual",
      "deseos y peticiones",
      "interacción cultural",
    ],
    criteriosAvance: [
      "Distingue ため(に) de causa y ため(に) de propósito en contexto real",
      "Usa なら para condicionar contexto, diferenciándolo de たら sin confusión",
      "Aplica ～わけではない para matizar sin que se le sugiera la estructura",
      "Describe hábitos del pasado con Vタものだ de forma espontánea",
    ],
    proyectos: [
      {
        id: "cj-c-p1",
        nombre: "Una invención de mi país",
        nombreJa: "わが国の発明品",
        definicion: "El alumno presenta un invento real o muy conocido de su país: su historia, para qué sirve, y qué pasaría si no existiera. Usa Nによって受身, ため(に) y まま. 3 minutos.",
        formato: "presentación Zoom o video",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["Nによって受身", "ため(に)", "まま", "inventos y tecnología"],
        checklist: [
          "タスク遂行 · Presenta el invento con contexto histórico o cultural",
          "タスク遂行 · Usa Nによって al menos una vez para describir quién lo creó o cómo surgió",
          "正確さ · ため(に) y まま bien formados",
          "流暢さ · La presentación fluye con naturalidad y sin lectura directa",
        ],
      },
      {
        id: "cj-c-p2",
        nombre: "Historias de malentendidos",
        nombreJa: "誤解トークセッション",
        definicion: "Cada alumno comparte una historia de malentendido cultural real o imaginado: un gesto incomprendido, una costumbre rara o una reacción inesperada. Usa 〜わけではない, あいだに y Nによって. 6 minutos en grupo.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["〜わけではない", "あいだに", "Nによって", "malentendidos culturales"],
        checklist: [
          "Comparte una historia comprensible para el grupo",
          "Usa わけではない para aclarar o matizar al menos una vez",
          "Reacciona a la historia de al menos un compañero",
          "Mantiene el intercambio en japonés durante toda la conversación",
        ],
      },
      {
        id: "cj-c-p3",
        nombre: "Operación mercadillo",
        nombreJa: "フリマ大作戦",
        definicion: "El grupo planea y simula un mercadillo virtual: cada alumno elige qué vendería y por qué, negocia con los demás usando なら, といっても y Vテほしい, y cuenta algo que antes le encantaba (Vタものだ). 5–6 minutos.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["なら", "といっても", "Vタものだ", "Vテほしい"],
        checklist: [
          "Propone al menos 1 artículo con razones concretas",
          "Usa なら o といっても en la negociación",
          "Menciona algo del pasado con Vタものだ",
          "Mantiene el intercambio activo en japonés",
        ],
      },
    ],
  },
  {
    id: "cj-d",
    numero: 12,
    nombre: "Sociedad y precisión lingüística",
    nombreJa: "社会とことば",
    nivel: 3,
    cefr: "B1",
    jlpt: "N3",
    lecciones: [],
    canDo: "Puedes discutir cambios sociales con vocabulario formal, usar 使役受身 y Na/Nである en contexto, ajustar el registro del habla entre casual y formal usando 敬語, y expresar normas y alternativas con べきだ y ずに.",
    vocabTemas: [
      "roles de género y trabajo doméstico",
      "lenguaje formal y keigo avanzado",
      "errores lingüísticos y aprendizaje",
      "cambios sociales y tendencias",
    ],
    competencias: [
      "cambios sociales",
      "registro formal",
      "keigo avanzado",
      "使役受身",
      "べきだ",
      "ずに",
      "matices lingüísticos",
      "Na/Nである",
    ],
    criteriosAvance: [
      "Usa 使役受身 de forma espontánea para describir una situación en que se le forzó a hacer algo",
      "Distingue Na/Nである del copular de registro neutro al presentar ideas formalmente",
      "Aplica べきだ para expresar normas y deberes sociales con naturalidad",
      "Ajusta el registro del habla de casual a formal según el interlocutor durante una conversación",
    ],
    proyectos: [
      {
        id: "cj-d-p1",
        nombre: "Hablemos de los cambios sociales",
        nombreJa: "社会の変化を語ろう",
        definicion: "Conversación grupal sobre un cambio social relevante (roles de género, trabajo, tecnología, educación): cada alumno expone su postura usando にともなって, 接続詞 (つまり/一方), Na/Nである y 使役受身. 6–8 minutos.",
        formato: "conversación Zoom",
        evalTipo: "interaccion",
        evalNota: "Tarea de interacción (やりとり): se evalúa solo si logras comunicarte y completar la tarea. No se penalizan errores de gramática.",
        evalDimensiones: ["タスク遂行 (cumplimiento de la tarea)"],
        competencias: ["にともなって", "接続詞", "Na/Nである", "使役受身"],
        checklist: [
          "Expone su postura sobre el cambio social con claridad",
          "Usa にともなって o un 接続詞 para conectar ideas",
          "Responde al argumento de al menos un compañero",
          "Mantiene el intercambio en japonés durante toda la conversación",
        ],
      },
      {
        id: "cj-d-p2",
        nombre: "Mis errores de japonés",
        nombreJa: "日本語ミス体験談",
        definicion: "El alumno presenta una historia real o imaginada de un error lingüístico en japonés (propio o ajeno): qué debería haberse dicho (べきだ), cómo debería haberse evitado (ずに), y qué alternativa existe (の代わりに). 3–4 minutos.",
        formato: "presentación Zoom",
        evalTipo: "produccion",
        evalNota: "Tarea de producción (産出): se evalúa el cumplimiento de la tarea + precisión + fluidez, porque es una entrega preparada.",
        evalDimensiones: ["タスク遂行 (cumplimiento)", "正確さ (precisión)", "流暢さ (fluidez)"],
        competencias: ["べきだ", "ずに", "の代わりに", "敬語"],
        checklist: [
          "タスク遂行 · Cuenta el error con suficiente contexto para que el grupo lo entienda",
          "タスク遂行 · Explica qué debería haberse dicho o hecho de otra forma",
          "正確さ · べきだ y ずに bien formados",
          "流暢さ · La presentación es fluida y tiene momentos de humor o reflexión",
        ],
      },
    ],
  },
];

export function getCurrentCurriculumModule(currentLesson: number | null): CurriculumModule {
  if (currentLesson == null) return CURRICULUM_MODULES[0];
  const match = CURRICULUM_MODULES.find((m) => m.lecciones.includes(currentLesson));
  if (match) return match;
  const maxLesson = Math.max(...CURRICULUM_MODULES.flatMap((m) => m.lecciones));
  if (currentLesson > maxLesson) return CURRICULUM_MODULES[CURRICULUM_MODULES.length - 1];
  return CURRICULUM_MODULES[0];
}

export function getCurriculumModuleByNumber(numero: number | null | undefined): CurriculumModule | undefined {
  if (numero == null) return undefined;
  return CURRICULUM_MODULES.find((m) => m.numero === numero);
}

export function getCurriculumModuleIndex(currentLesson: number | null): number {
  const current = getCurrentCurriculumModule(currentLesson);
  return CURRICULUM_MODULES.findIndex((m) => m.id === current.id);
}

export function isCurriculumModuleCompleted(module: CurriculumModule, currentLesson: number | null): boolean {
  if (currentLesson == null) return false;
  const moduleMaxLesson = Math.max(...module.lecciones);
  return moduleMaxLesson < currentLesson && !module.lecciones.includes(currentLesson);
}

export function isCurriculumModuleCurrent(module: CurriculumModule, currentLesson: number | null): boolean {
  return getCurrentCurriculumModule(currentLesson).id === module.id;
}

export function getModuleById(id: string): CurriculumModule | undefined {
  return CURRICULUM_MODULES.find((m) => m.id === id);
}
