export type GenkiKanjiItem = { kanji: string; hira: string; es: string };

export const GENKI_KANJI_BY_LESSON: Record<number, GenkiKanjiItem[]> = {
  3: [
    { kanji: "一", hira: "いち", es: "uno" },
    { kanji: "一時", hira: "いちじ", es: "la una" },
    { kanji: "二", hira: "に", es: "dos" },
    { kanji: "二時", hira: "にじ", es: "las dos" },
    { kanji: "三", hira: "さん", es: "tres" },
    { kanji: "三時", hira: "さんじ", es: "las tres" },
    { kanji: "四", hira: "よん", es: "cuatro" },
    { kanji: "四時", hira: "よじ", es: "las cuatro" },
    { kanji: "五", hira: "ご", es: "cinco" },
    { kanji: "五時", hira: "ごじ", es: "las cinco" },
    { kanji: "六", hira: "ろく", es: "seis" },
    { kanji: "六時", hira: "ろくじ", es: "las seis" },
    { kanji: "七", hira: "なな", es: "siete" },
    { kanji: "七時", hira: "しちじ", es: "las siete" },
    { kanji: "八", hira: "はち", es: "ocho" },
    { kanji: "八時", hira: "はちじ", es: "las ocho" },
    { kanji: "九", hira: "きゅう", es: "nueve" },
    { kanji: "九時", hira: "くじ", es: "las nueve" },
    { kanji: "十", hira: "じゅう", es: "diez" },
    { kanji: "十時", hira: "じゅうじ", es: "las diez" },
    { kanji: "百", hira: "ひゃく", es: "cien" },
    { kanji: "千", hira: "せん", es: "mil" },
    { kanji: "一万", hira: "いちまん", es: "diez mil" },
    { kanji: "円", hira: "えん", es: "yen" },
  ],
  4: [
    { kanji: "日本", hira: "にほん", es: "Japón" },
    { kanji: "本", hira: "ほん", es: "libro" },
    { kanji: "日本人", hira: "にほんじん", es: "japonés (persona)" },
    { kanji: "月曜日", hira: "げつようび", es: "lunes" },
    { kanji: "火曜日", hira: "かようび", es: "martes" },
    { kanji: "水曜日", hira: "すいようび", es: "miércoles" },
    { kanji: "木曜日", hira: "もくようび", es: "jueves" },
    { kanji: "金曜日", hira: "きんようび", es: "viernes" },
    { kanji: "土曜日", hira: "どようび", es: "sábado" },
    { kanji: "日曜日", hira: "にちようび", es: "domingo" },
    { kanji: "上", hira: "うえ", es: "arriba / encima" },
    { kanji: "下", hira: "した", es: "abajo / debajo" },
    { kanji: "中", hira: "なか", es: "dentro / en medio" },
    { kanji: "三時半", hira: "さんじはん", es: "las tres y media" },
  ],
  5: [
    { kanji: "山", hira: "やま", es: "montaña" },
    { kanji: "川", hira: "かわ", es: "río" },
    { kanji: "元気な", hira: "げんきな", es: "sano / con energía" },
    { kanji: "天気", hira: "てんき", es: "clima" },
    { kanji: "私", hira: "わたし", es: "yo" },
    { kanji: "今", hira: "いま", es: "ahora" },
    { kanji: "田中さん", hira: "たなかさん", es: "Sr. Tanaka" },
    { kanji: "女の人", hira: "おんなのひと", es: "mujer" },
    { kanji: "男の人", hira: "おとこのひと", es: "hombre" },
    { kanji: "見る", hira: "みる", es: "ver" },
    { kanji: "行く", hira: "いく", es: "ir" },
    { kanji: "食べる", hira: "たべる", es: "comer" },
    { kanji: "飲む", hira: "のむ", es: "beber" },
  ],
  6: [
    { kanji: "東", hira: "ひがし", es: "este" },
    { kanji: "西", hira: "にし", es: "oeste" },
    { kanji: "南", hira: "みなみ", es: "sur" },
    { kanji: "北", hira: "きた", es: "norte" },
    { kanji: "出口", hira: "でぐち", es: "salida" },
    { kanji: "出る", hira: "でる", es: "salir" },
    { kanji: "右", hira: "みぎ", es: "derecha" },
    { kanji: "左", hira: "ひだり", es: "izquierda" },
    { kanji: "五分", hira: "ごふん", es: "cinco minutos" },
    { kanji: "先生", hira: "せんせい", es: "profesor" },
    { kanji: "学生", hira: "がくせい", es: "estudiante" },
    { kanji: "大きい", hira: "おおきい", es: "grande" },
    { kanji: "大学", hira: "だいがく", es: "universidad" },
    { kanji: "外国", hira: "がいこく", es: "país extranjero" },
    { kanji: "中国", hira: "ちゅうごく", es: "China" },
  ],
  7: [
    { kanji: "東京", hira: "とうきょう", es: "Tokio" },
    { kanji: "子ども", hira: "こども", es: "niño" },
    { kanji: "小さい", hira: "ちいさい", es: "pequeño" },
    { kanji: "会う", hira: "あう", es: "encontrarse / ver a alguien" },
    { kanji: "会社", hira: "かいしゃ", es: "empresa" },
    { kanji: "父", hira: "ちち", es: "mi padre" },
    { kanji: "母", hira: "はは", es: "mi madre" },
    { kanji: "高い", hira: "たかい", es: "caro / alto" },
    { kanji: "学校", hira: "がっこう", es: "escuela" },
    { kanji: "毎日", hira: "まいにち", es: "todos los días" },
    { kanji: "日本語", hira: "にほんご", es: "idioma japonés" },
    { kanji: "文学", hira: "ぶんがく", es: "literatura" },
    { kanji: "帰る", hira: "かえる", es: "volver / regresar" },
    { kanji: "入る", hira: "はいる", es: "entrar" },
  ],
  8: [
    { kanji: "会社員", hira: "かいしゃいん", es: "oficinista" },
    { kanji: "新しい", hira: "あたらしい", es: "nuevo" },
    { kanji: "聞く", hira: "きく", es: "escuchar" },
    { kanji: "作る", hira: "つくる", es: "hacer / producir" },
    { kanji: "仕事", hira: "しごと", es: "trabajo" },
    { kanji: "電車", hira: "でんしゃ", es: "tren" },
    { kanji: "車", hira: "くるま", es: "coche / automóvil" },
    { kanji: "休む", hira: "やすむ", es: "descansar" },
    { kanji: "言う", hira: "いう", es: "decir" },
    { kanji: "読む", hira: "よむ", es: "leer" },
    { kanji: "思う", hira: "おもう", es: "pensar" },
    { kanji: "次", hira: "つぎ", es: "siguiente" },
    { kanji: "何", hira: "なに", es: "qué" },
  ],
  9: [
    { kanji: "午前", hira: "ごぜん", es: "A.M." },
    { kanji: "午後", hira: "ごご", es: "P.M." },
    { kanji: "名前", hira: "なまえ", es: "nombre" },
    { kanji: "白い", hira: "しろい", es: "blanco" },
    { kanji: "雨", hira: "あめ", es: "lluvia" },
    { kanji: "書く", hira: "かく", es: "escribir" },
    { kanji: "友だち", hira: "ともだち", es: "amigo" },
    { kanji: "時間", hira: "じかん", es: "tiempo / horas" },
    { kanji: "家", hira: "いえ", es: "casa" },
    { kanji: "少し", hira: "すこし", es: "un poco" },
    { kanji: "古い", hira: "ふるい", es: "viejo" },
    { kanji: "知る", hira: "しる", es: "saber" },
    { kanji: "来る", hira: "くる", es: "venir" },
  ],
  10: [
    { kanji: "住む", hira: "すむ", es: "vivir / residir" },
    { kanji: "お正月", hira: "おしょうがつ", es: "Año Nuevo" },
    { kanji: "三年生", hira: "さんねんせい", es: "estudiante de tercer año" },
    { kanji: "売る", hira: "うる", es: "vender" },
    { kanji: "買う", hira: "かう", es: "comprar" },
    { kanji: "町", hira: "まち", es: "pueblo / ciudad" },
    { kanji: "長い", hira: "ながい", es: "largo" },
    { kanji: "道", hira: "みち", es: "camino / calle" },
    { kanji: "自分", hira: "じぶん", es: "uno mismo" },
    { kanji: "夜", hira: "よる", es: "noche" },
    { kanji: "朝", hira: "あさ", es: "mañana" },
    { kanji: "持つ", hira: "もつ", es: "cargar / tener" },
  ],
  11: [
    { kanji: "手紙", hira: "てがみ", es: "carta" },
    { kanji: "好きな", hira: "すきな", es: "gustar / favorito" },
    { kanji: "近い", hira: "ちかい", es: "cerca" },
    { kanji: "明るい", hira: "あかるい", es: "brillante / alegre" },
    { kanji: "病院", hira: "びょういん", es: "hospital" },
    { kanji: "映画", hira: "えいが", es: "película" },
    { kanji: "歌う", hira: "うたう", es: "cantar" },
    { kanji: "市役所", hira: "しやくしょ", es: "ayuntamiento" },
    { kanji: "所", hira: "ところ", es: "lugar" },
    { kanji: "勉強する", hira: "べんきょうする", es: "estudiar" },
    { kanji: "有名な", hira: "ゆうめいな", es: "famoso" },
    { kanji: "旅行", hira: "りょこう", es: "viaje" },
  ],
  12: [
    { kanji: "昔", hira: "むかし", es: "hace mucho tiempo" },
    { kanji: "時々", hira: "ときどき", es: "a veces" },
    { kanji: "神社", hira: "じんじゃ", es: "santuario" },
    { kanji: "早い", hira: "はやい", es: "temprano" },
    { kanji: "起きる", hira: "おきる", es: "levantarse" },
    { kanji: "牛乳", hira: "ぎゅうにゅう", es: "leche" },
    { kanji: "使う", hira: "つかう", es: "usar" },
    { kanji: "働く", hira: "はたらく", es: "trabajar" },
    { kanji: "連れて帰る", hira: "つれてかえる", es: "llevar (a alguien) a casa" },
    { kanji: "別れる", hira: "わかれる", es: "separarse / romper" },
    { kanji: "一度", hira: "いちど", es: "una vez" },
    { kanji: "赤い", hira: "あかい", es: "rojo" },
    { kanji: "青い", hira: "あおい", es: "azul" },
    { kanji: "色", hira: "いろ", es: "color" },
  ],
};
