export type GenkiVocabItem = { hira: string; kanji: string; es: string };

export const GENKI_VOCAB_BY_LESSON: Record<number, GenkiVocabItem[]> = {
  1: [
    { hira: "だいがく", kanji: "大学", es: "universidad; instituto" },
    { hira: "こうこう", kanji: "高校", es: "escuela secundaria superior" },
    { hira: "がくせい", kanji: "学生", es: "estudiante" },
    { hira: "だいがくせい", kanji: "大学生", es: "estudiante universitario" },
    { hira: "りゅうがくせい", kanji: "留学生", es: "estudiante extranjero/a" },
    { hira: "せんせい", kanji: "先生", es: "profesor/a" },
    { hira: "…ねんせい", kanji: "…年生", es: "estudiante de … año" },
    { hira: "いちねんせい", kanji: "一年生", es: "estudiante de primer año" },
    { hira: "せんこう", kanji: "専攻", es: "especialidad" },
    { hira: "わたし", kanji: "私", es: "yo" },
    { hira: "ともだち", kanji: "友だち", es: "amigo/a" },
    { hira: "…さん", kanji: "", es: "Sr./Sra. …" },
    { hira: "…じん", kanji: "…人", es: "persona de … [como gentilicio]" },
    { hira: "にほんじん", kanji: "日本人", es: "los japoneses" },
    { hira: "いま", kanji: "今", es: "ahora" },
    { hira: "ごぜん", kanji: "午前", es: "A.M." },
    { hira: "ごご", kanji: "午後", es: "P.M." },
    { hira: "…じ", kanji: "…時", es: "… en punto" },
    { hira: "いちじ", kanji: "一時", es: "la una" },
    { hira: "はん", kanji: "半", es: "y media" },
    { hira: "にじはん", kanji: "二時半", es: "las dos y media" },
    { hira: "にほん", kanji: "日本", es: "Japón" },
    { hira: "アメリカ", kanji: "", es: "EE.UU." },
    { hira: "…ご", kanji: "…語", es: "idioma …" },
    { hira: "にほんご", kanji: "日本語", es: "idioma japonés" },
    { hira: "…さい", kanji: "…歳", es: "… años de edad" },
    { hira: "でんわ", kanji: "電話", es: "teléfono" },
    { hira: "…ばん", kanji: "…番", es: "número …" },
    { hira: "ばんごう", kanji: "番号", es: "número" },
    { hira: "なまえ", kanji: "名前", es: "nombre" },
    { hira: "なん/なに", kanji: "何", es: "qué" },
    { hira: "あのう", kanji: "", es: "um…" },
    { hira: "はい", kanji: "", es: "sí" },
    { hira: "そうです", kanji: "", es: "Así es." },
    { hira: "そうですか", kanji: "", es: "Ya veo.; ¿Es así?" },
    { hira: "イギリス", kanji: "", es: "Gran Bretaña" },
    { hira: "オーストラリア", kanji: "", es: "Australia" },
    { hira: "かんこく", kanji: "韓国", es: "Corea (del Sur)" },
    { hira: "カナダ", kanji: "", es: "Canadá" },
    { hira: "ちゅうごく", kanji: "中国", es: "China" },
    { hira: "インド", kanji: "", es: "la India" },
    { hira: "エジプト", kanji: "", es: "Egipto" },
    { hira: "フィリピン", kanji: "", es: "Filipinas" },
    { hira: "アジアけんきゅう", kanji: "アジア研究", es: "estudios asiáticos" },
    { hira: "けいざい", kanji: "経済", es: "economía" },
    { hira: "こうがく", kanji: "工学", es: "ingeniería" },
    { hira: "こくさいかんけい", kanji: "国際関係", es: "relaciones internacionales" },
    { hira: "コンピューター", kanji: "", es: "informática" },
    { hira: "せいじ", kanji: "政治", es: "política" },
    { hira: "せいぶつがく", kanji: "生物学", es: "biología" },
    { hira: "ビジネス", kanji: "", es: "negocios" },
    { hira: "ぶんがく", kanji: "文学", es: "literatura" },
    { hira: "れきし", kanji: "歴史", es: "historia" },
    { hira: "いしゃ", kanji: "医者", es: "doctor/a" },
    { hira: "かいしゃいん", kanji: "会社員", es: "oficinista" },
    { hira: "かんごし", kanji: "看護師", es: "enfermero/a" },
    { hira: "こうこうせい", kanji: "高校生", es: "estudiante de secundaria superior" },
    { hira: "しゅふ", kanji: "主婦", es: "ama de casa" },
    { hira: "だいがくいんせい", kanji: "大学院生", es: "estudiante de posgrado" },
    { hira: "べんごし", kanji: "弁護士", es: "abogado/a" },
    { hira: "おかあさん", kanji: "お母さん", es: "madre" },
    { hira: "おとうさん", kanji: "お父さん", es: "padre" },
    { hira: "おねえさん", kanji: "お姉さん", es: "hermana mayor" },
    { hira: "おにいさん", kanji: "お兄さん", es: "hermano mayor" },
    { hira: "いもうと", kanji: "妹", es: "hermana menor" },
    { hira: "おとうと", kanji: "弟", es: "hermano menor" },
  ],
  2: [
    { hira: "これ", kanji: "", es: "este" },
    { hira: "それ", kanji: "", es: "ese" },
    { hira: "あれ", kanji: "", es: "aquel (el de allí)" },
    { hira: "どれ", kanji: "", es: "cuál" },
    { hira: "この", kanji: "", es: "este …" },
    { hira: "その", kanji: "", es: "ese …" },
    { hira: "あの", kanji: "", es: "aquel … (de allí)" },
    { hira: "どの", kanji: "", es: "cuál …" },
    { hira: "ここ", kanji: "", es: "aquí" },
    { hira: "そこ", kanji: "", es: "ahí" },
    { hira: "あそこ", kanji: "", es: "allí" },
    { hira: "どこ", kanji: "", es: "dónde" },
    { hira: "だれ", kanji: "", es: "quién" },
    { hira: "おいしい", kanji: "", es: "delicioso" },
    { hira: "さかな", kanji: "魚", es: "pescado" },
    { hira: "とんかつ", kanji: "", es: "chuleta de cerdo" },
    { hira: "にく", kanji: "肉", es: "carne" },
    { hira: "メニュー", kanji: "", es: "menú" },
    { hira: "やさい", kanji: "野菜", es: "verdura" },
    { hira: "かさ", kanji: "傘", es: "paraguas" },
    { hira: "かばん", kanji: "", es: "bolsa; bolso" },
    { hira: "くつ", kanji: "靴", es: "zapatos" },
    { hira: "さいふ", kanji: "財布", es: "billetera" },
    { hira: "ジーンズ", kanji: "", es: "jeans; vaqueros" },
    { hira: "じてんしゃ", kanji: "自転車", es: "bicicleta" },
    { hira: "しんぶん", kanji: "新聞", es: "periódico" },
    { hira: "スマホ", kanji: "", es: "smartphone; móvil; celular" },
    { hira: "ティーシャツ", kanji: "", es: "camiseta; playera" },
    { hira: "とけい", kanji: "時計", es: "reloj" },
    { hira: "ノート", kanji: "", es: "cuaderno" },
    { hira: "ペン", kanji: "", es: "pluma; bolígrafo" },
    { hira: "ぼうし", kanji: "帽子", es: "sombrero; gorra" },
    { hira: "ほん", kanji: "本", es: "libro" },
    { hira: "ぎんこう", kanji: "銀行", es: "banco" },
    { hira: "コンビニ", kanji: "", es: "tienda de conveniencia" },
    { hira: "トイレ", kanji: "", es: "cuarto de baño; WC" },
    { hira: "としょかん", kanji: "図書館", es: "biblioteca" },
    { hira: "ゆうびんきょく", kanji: "郵便局", es: "oficina de correos" },
    { hira: "イギリス", kanji: "", es: "Gran Bretaña" },
    { hira: "かんこく", kanji: "韓国", es: "Corea (del Sur)" },
    { hira: "ちゅうごく", kanji: "中国", es: "China" },
    { hira: "えいご", kanji: "英語", es: "inglés (idioma)" },
    { hira: "けいざい", kanji: "経済", es: "economía" },
    { hira: "コンピューター", kanji: "", es: "informática" },
    { hira: "ビジネス", kanji: "", es: "negocios" },
    { hira: "れきし", kanji: "歴史", es: "historia" },
    { hira: "おかあさん", kanji: "お母さん", es: "madre" },
    { hira: "おとうさん", kanji: "お父さん", es: "padre" },
    { hira: "いくら", kanji: "", es: "cuánto" },
    { hira: "…えん", kanji: "…円", es: "… yenes" },
    { hira: "たかい", kanji: "高い", es: "caro; alto" },
    { hira: "いらっしゃいませ", kanji: "", es: "Bienvenido (a nuestra tienda)." },
    { hira: "(…を)おねがいします", kanji: "", es: "…, por favor." },
    { hira: "(…を)ください", kanji: "", es: "Por favor, deme …" },
    { hira: "じゃあ", kanji: "", es: "entonces …; si ese es el caso, …" },
    { hira: "どうぞ", kanji: "", es: "Por favor.; Aquí tiene." },
    { hira: "どうも", kanji: "", es: "Gracias." },
  ],
  3: [
    { hira: "えいが", kanji: "映画", es: "película" },
    { hira: "おんがく", kanji: "音楽", es: "música" },
    { hira: "ざっし", kanji: "雑誌", es: "revista" },
    { hira: "スポーツ", kanji: "", es: "deportes" },
    { hira: "デート", kanji: "", es: "cita (romántica)" },
    { hira: "テニス", kanji: "", es: "tenis" },
    { hira: "テレビ", kanji: "", es: "TV" },
    { hira: "アイスクリーム", kanji: "", es: "helado" },
    { hira: "ハンバーガー", kanji: "", es: "hamburguesa" },
    { hira: "おさけ", kanji: "お酒", es: "sake; bebida alcohólica" },
    { hira: "おちゃ", kanji: "お茶", es: "té verde" },
    { hira: "コーヒー", kanji: "", es: "café" },
    { hira: "みず", kanji: "水", es: "agua" },
    { hira: "あさごはん", kanji: "朝ごはん", es: "desayuno" },
    { hira: "ひるごはん", kanji: "昼ごはん", es: "almuerzo" },
    { hira: "ばんごはん", kanji: "晩ごはん", es: "cena" },
    { hira: "いえ", kanji: "家", es: "hogar; casa" },
    { hira: "うち", kanji: "家", es: "hogar; casa; mi casa" },
    { hira: "がっこう", kanji: "学校", es: "escuela" },
    { hira: "カフェ", kanji: "", es: "cafetería" },
    { hira: "あさ", kanji: "朝", es: "mañana" },
    { hira: "きょう", kanji: "今日", es: "hoy" },
    { hira: "ごぜんちゅう", kanji: "午前中", es: "por la mañana" },
    { hira: "こんばん", kanji: "今晩", es: "esta noche" },
    { hira: "まいにち", kanji: "毎日", es: "todos los días" },
    { hira: "まいばん", kanji: "毎晩", es: "todas las noches" },
    { hira: "しゅうまつ", kanji: "週末", es: "fin de semana" },
    { hira: "どようび", kanji: "土曜日", es: "sábado" },
    { hira: "にちようび", kanji: "日曜日", es: "domingo" },
    { hira: "いつ", kanji: "", es: "cuándo" },
    { hira: "ごろ", kanji: "", es: "sobre las …" },
    { hira: "いく", kanji: "行く", es: "ir (destino に/へ)" },
    { hira: "かえる", kanji: "帰る", es: "volver; regresar (destino に/へ)" },
    { hira: "きく", kanji: "聞く", es: "escuchar; oír (～を)" },
    { hira: "のむ", kanji: "飲む", es: "tomar; beber (～を)" },
    { hira: "はなす", kanji: "話す", es: "hablar; conversar (idioma を/で)" },
    { hira: "よむ", kanji: "読む", es: "leer (～を)" },
    { hira: "おきる", kanji: "起きる", es: "levantarse" },
    { hira: "たべる", kanji: "食べる", es: "comer (～を)" },
    { hira: "ねる", kanji: "寝る", es: "dormir; irse a dormir" },
    { hira: "みる", kanji: "見る", es: "ver; mirar; observar (～を)" },
    { hira: "くる", kanji: "来る", es: "venir (destino に/へ)" },
    { hira: "する", kanji: "", es: "hacer (～を)" },
    { hira: "べんきょうする", kanji: "勉強する", es: "estudiar (～を)" },
    { hira: "いい", kanji: "", es: "bueno" },
    { hira: "はやい", kanji: "早い", es: "temprano" },
    { hira: "あまり", kanji: "", es: "+ negativo: no mucho; no tanto" },
    { hira: "ぜんぜん", kanji: "全然", es: "+ negativo: no, en absoluto" },
    { hira: "たいてい", kanji: "", es: "normalmente" },
    { hira: "ちょっと", kanji: "", es: "un poco" },
    { hira: "ときどき", kanji: "時々", es: "a veces" },
    { hira: "よく", kanji: "", es: "a menudo; mucho" },
    { hira: "そうですね", kanji: "", es: "Así es.; A ver." },
    { hira: "でも", kanji: "", es: "pero" },
    { hira: "どうですか", kanji: "", es: "¿Qué tal…?; ¿Cómo es…?" },
    { hira: "ええ", kanji: "", es: "sí" },
  ],
  4: [
    { hira: "ゲーム", kanji: "", es: "juego" },
    { hira: "アルバイト", kanji: "", es: "trabajo a tiempo parcial" },
    { hira: "かいもの", kanji: "買い物", es: "compras" },
    { hira: "クラス", kanji: "", es: "clase" },
    { hira: "いぬ", kanji: "犬", es: "perro/a" },
    { hira: "ねこ", kanji: "猫", es: "gato/a" },
    { hira: "ひと", kanji: "人", es: "persona" },
    { hira: "こども", kanji: "子供", es: "niño/a" },
    { hira: "あなた", kanji: "", es: "usted" },
    { hira: "いす", kanji: "椅子", es: "silla" },
    { hira: "つくえ", kanji: "机", es: "escritorio" },
    { hira: "しゃしん", kanji: "写真", es: "imagen; fotografía" },
    { hira: "はな", kanji: "花", es: "flor" },
    { hira: "レポート", kanji: "", es: "informe" },
    { hira: "ごはん", kanji: "ご飯", es: "arroz; comida" },
    { hira: "パン", kanji: "", es: "pan" },
    { hira: "おてら", kanji: "お寺", es: "templo" },
    { hira: "こうえん", kanji: "公園", es: "parque" },
    { hira: "スーパー", kanji: "", es: "supermercado" },
    { hira: "バスてい", kanji: "バス停", es: "parada de autobús" },
    { hira: "びょういん", kanji: "病院", es: "hospital" },
    { hira: "ホテル", kanji: "", es: "hotel" },
    { hira: "ほんや", kanji: "本屋", es: "librería" },
    { hira: "まち", kanji: "町", es: "pueblo; ciudad" },
    { hira: "レストラン", kanji: "", es: "restaurante" },
    { hira: "きのう", kanji: "昨日", es: "ayer" },
    { hira: "…じかん", kanji: "…時間", es: "… horas" },
    { hira: "いちじかん", kanji: "一時間", es: "una hora" },
    { hira: "せんしゅう", kanji: "先週", es: "la semana pasada" },
    { hira: "とき", kanji: "時", es: "cuando …; durante …" },
    { hira: "げつようび", kanji: "月曜日", es: "lunes" },
    { hira: "かようび", kanji: "火曜日", es: "martes" },
    { hira: "すいようび", kanji: "水曜日", es: "miércoles" },
    { hira: "もくようび", kanji: "木曜日", es: "jueves" },
    { hira: "きんようび", kanji: "金曜日", es: "viernes" },
    { hira: "あう", kanji: "会う", es: "conocer; ver (a una persona) (persona に)" },
    { hira: "ある", kanji: "", es: "hay… (lugar に cosa が)" },
    { hira: "かう", kanji: "買う", es: "comprar (～を)" },
    { hira: "かく", kanji: "書く", es: "escribir (persona に cosa を)" },
    { hira: "とる", kanji: "撮る", es: "tomar (una foto) (～を)" },
    { hira: "まつ", kanji: "待つ", es: "esperar (～を)" },
    { hira: "わかる", kanji: "分かる", es: "entender (～が)" },
    { hira: "いる", kanji: "", es: "(una persona) está en …; se queda en … (lugar に persona が)" },
    { hira: "ぐらい", kanji: "", es: "alrededor de (medida aproximada)" },
    { hira: "ごめんなさい", kanji: "", es: "Lo siento.; Perdón." },
    { hira: "それから", kanji: "", es: "y luego" },
    { hira: "だから", kanji: "", es: "así que; por lo tanto" },
    { hira: "たくさん", kanji: "", es: "muchos; mucho" },
    { hira: "と", kanji: "", es: "junto con (una persona); y" },
    { hira: "どうして", kanji: "", es: "por qué" },
    { hira: "ひとりで", kanji: "一人で", es: "solo" },
    { hira: "もしもし", kanji: "", es: "¿Aló?; ¿Bueno? (contestando el teléfono)" },
    { hira: "みぎ", kanji: "右", es: "derecha (～の)" },
    { hira: "ひだり", kanji: "左", es: "izquierda (～の)" },
    { hira: "まえ", kanji: "前", es: "delante de (～の)" },
    { hira: "うしろ", kanji: "後ろ", es: "atrás (～の)" },
    { hira: "なか", kanji: "中", es: "adentro (～の)" },
    { hira: "うえ", kanji: "上", es: "sobre (～の)" },
    { hira: "した", kanji: "下", es: "bajo (～の)" },
    { hira: "ちかく", kanji: "近く", es: "cerca; cercano (～の)" },
    { hira: "となり", kanji: "隣", es: "siguiente (～の)" },
    { hira: "あいだ", kanji: "間", es: "entre (AとBの)" },
  ],
  5: [
    { hira: "たべもの", kanji: "食べ物", es: "comida" },
    { hira: "のみもの", kanji: "飲み物", es: "bebida" },
    { hira: "くだもの", kanji: "果物", es: "fruta" },
    { hira: "やすみ", kanji: "休み", es: "vacaciones; día libre; ausencia" },
    { hira: "りょこう", kanji: "旅行", es: "viaje" },
    { hira: "うみ", kanji: "海", es: "mar" },
    { hira: "サーフィン", kanji: "", es: "surf" },
    { hira: "おみやげ", kanji: "お土産", es: "recuerdo; souvenir" },
    { hira: "バス", kanji: "", es: "autobús" },
    { hira: "てんき", kanji: "天気", es: "tiempo (atmosférico)" },
    { hira: "しゅくだい", kanji: "宿題", es: "deberes; tareas" },
    { hira: "テスト", kanji: "", es: "examen" },
    { hira: "たんじょうび", kanji: "誕生日", es: "cumpleaños" },
    { hira: "へや", kanji: "部屋", es: "habitación" },
    { hira: "ぼく", kanji: "僕", es: "yo (utilizado por los hombres)" },
    { hira: "エル", kanji: "Ｌ", es: "talla L" },
    { hira: "あたらしい", kanji: "新しい", es: "nuevo" },
    { hira: "ふるい", kanji: "古い", es: "viejo (cosa, no se usa para personas)" },
    { hira: "あつい", kanji: "暑い", es: "caluroso (tiempo)" },
    { hira: "さむい", kanji: "寒い", es: "frío (tiempo, no cosas)" },
    { hira: "あつい", kanji: "熱い", es: "caliente (cosa)" },
    { hira: "いそがしい", kanji: "忙しい", es: "ocupado (personas/días)" },
    { hira: "おおきい", kanji: "大きい", es: "grande" },
    { hira: "ちいさい", kanji: "小さい", es: "pequeño" },
    { hira: "おもしろい", kanji: "面白い", es: "interesante; divertido" },
    { hira: "つまらない", kanji: "", es: "aburrido" },
    { hira: "やさしい", kanji: "優しい", es: "fácil (problema); amable (persona)" },
    { hira: "むずかしい", kanji: "難しい", es: "difícil" },
    { hira: "かっこいい", kanji: "", es: "guapo (se conjuga como いい)" },
    { hira: "こわい", kanji: "怖い", es: "espeluznante; que da miedo" },
    { hira: "たのしい", kanji: "楽しい", es: "divertido" },
    { hira: "やすい", kanji: "安い", es: "económico; barato (cosa)" },
    { hira: "すき（な）", kanji: "好き（な）", es: "gustar (～が)" },
    { hira: "きらい（な）", kanji: "嫌い（な）", es: "no gustar; disgustar (～が)" },
    { hira: "だいすき（な）", kanji: "大好き（な）", es: "gustar mucho (～が)" },
    { hira: "だいきらい（な）", kanji: "大嫌い（な）", es: "odiar (～が)" },
    { hira: "きれい（な）", kanji: "", es: "bonito; limpio" },
    { hira: "げんき（な）", kanji: "元気（な）", es: "saludable; enérgico" },
    { hira: "しずか（な）", kanji: "静か（な）", es: "tranquilo" },
    { hira: "にぎやか（な）", kanji: "", es: "animado" },
    { hira: "ひま（な）", kanji: "暇（な）", es: "desocupado; libre (tiempo)" },
    { hira: "およぐ", kanji: "泳ぐ", es: "nadar" },
    { hira: "きく", kanji: "聞く", es: "preguntar (persona に)" },
    { hira: "のる", kanji: "乗る", es: "montar; abordar (～に)" },
    { hira: "やる", kanji: "", es: "hacer; realizar (～を)" },
    { hira: "でかける", kanji: "出かける", es: "salir (a comer, al cine)" },
    { hira: "いっしょに", kanji: "一緒に", es: "juntos" },
    { hira: "すごく", kanji: "", es: "extremadamente" },
    { hira: "だいじょうぶ", kanji: "大丈夫", es: "Está bien.; No hay que preocuparse." },
    { hira: "とても", kanji: "", es: "muy" },
    { hira: "どんな", kanji: "", es: "qué tipo de…" },
    { hira: "…まい", kanji: "…枚", es: "[contador de objetos planos]" },
  ],
  6: [
    { hira: "かんじ", kanji: "漢字", es: "kanji; caracter chino" },
    { hira: "きょうかしょ", kanji: "教科書", es: "libro de texto" },
    { hira: "ページ", kanji: "", es: "página" },
    { hira: "つぎ", kanji: "次", es: "siguiente" },
    { hira: "おかね", kanji: "お金", es: "dinero" },
    { hira: "にもつ", kanji: "荷物", es: "equipaje" },
    { hira: "パソコン", kanji: "", es: "computadora personal" },
    { hira: "シャワー", kanji: "", es: "ducha" },
    { hira: "エアコン", kanji: "", es: "aire acondicionado" },
    { hira: "でんき", kanji: "電気", es: "electricidad; luz" },
    { hira: "まど", kanji: "窓", es: "ventana" },
    { hira: "でんしゃ", kanji: "電車", es: "tren" },
    { hira: "くに", kanji: "国", es: "país; lugar de origen" },
    { hira: "こんしゅう", kanji: "今週", es: "esta semana" },
    { hira: "らいしゅう", kanji: "来週", es: "la próxima semana" },
    { hira: "らいねん", kanji: "来年", es: "el próximo año" },
    { hira: "よる", kanji: "夜", es: "noche" },
    { hira: "たいへん（な）", kanji: "大変（な）", es: "difícil (situación)" },
    { hira: "あそぶ", kanji: "遊ぶ", es: "jugar; pasar un rato agradable" },
    { hira: "いそぐ", kanji: "急ぐ", es: "apresurarse" },
    { hira: "かえす", kanji: "返す", es: "devolver (persona に cosa を)" },
    { hira: "けす", kanji: "消す", es: "apagar; borrar (～を)" },
    { hira: "しぬ", kanji: "死ぬ", es: "morir" },
    { hira: "すわる", kanji: "座る", es: "sentarse (asiento に)" },
    { hira: "たつ", kanji: "立つ", es: "ponerse de pie" },
    { hira: "たばこをすう", kanji: "たばこを吸う", es: "fumar" },
    { hira: "つかう", kanji: "使う", es: "utilizar (～を)" },
    { hira: "てつだう", kanji: "手伝う", es: "ayudar (persona/tarea を)" },
    { hira: "はいる", kanji: "入る", es: "entrar (～に)" },
    { hira: "もつ", kanji: "持つ", es: "llevar; sostener (～を)" },
    { hira: "やすむ", kanji: "休む", es: "(1) faltar (a…) (～を) (2) descansar" },
    { hira: "あける", kanji: "開ける", es: "abrir (algo) (～を)" },
    { hira: "しめる", kanji: "閉める", es: "cerrar (algo) (～を)" },
    { hira: "おしえる", kanji: "教える", es: "enseñar; instruir (persona に cosa を)" },
    { hira: "わすれる", kanji: "忘れる", es: "olvidar; dejar atrás (～を)" },
    { hira: "おりる", kanji: "降りる", es: "bajarse (～を)" },
    { hira: "かりる", kanji: "借りる", es: "pedir prestado (persona に cosa を)" },
    { hira: "シャワーをあびる", kanji: "", es: "ducharse" },
    { hira: "つける", kanji: "", es: "encender (～を)" },
    { hira: "でんわをかける", kanji: "電話をかける", es: "llamar (～に)" },
    { hira: "つれてくる", kanji: "連れてくる", es: "traer (a una persona) (～を)" },
    { hira: "もってくる", kanji: "持ってくる", es: "traer (una cosa) (～を)" },
    { hira: "あとで", kanji: "後で", es: "después" },
    { hira: "すぐ", kanji: "", es: "de inmediato" },
    { hira: "ゆっくり", kanji: "", es: "despacio; con calma; sin prisas" },
    { hira: "けっこうです", kanji: "結構です", es: "Estaría bien.; No sería necesario." },
    { hira: "ほんとうですか", kanji: "本当ですか", es: "¿De verdad?" },
  ],
  7: [
    { hira: "かぞく", kanji: "家族", es: "familia" },
    { hira: "おじいさん", kanji: "", es: "abuelo; anciano" },
    { hira: "おばあさん", kanji: "", es: "abuela; anciana" },
    { hira: "おにいさん", kanji: "お兄さん", es: "hermano mayor" },
    { hira: "おねえさん", kanji: "お姉さん", es: "hermana mayor" },
    { hira: "ちち", kanji: "父", es: "(mi) padre" },
    { hira: "はは", kanji: "母", es: "(mi) madre" },
    { hira: "あに", kanji: "兄", es: "(mi) hermano mayor" },
    { hira: "あね", kanji: "姉", es: "(mi) hermana mayor" },
    { hira: "いもうと", kanji: "妹", es: "hermana menor" },
    { hira: "おとうと", kanji: "弟", es: "hermano menor" },
    { hira: "きょうだい", kanji: "兄弟", es: "hermanos y hermanas" },
    { hira: "おとこのひと", kanji: "男の人", es: "hombre" },
    { hira: "おんなのひと", kanji: "女の人", es: "mujer" },
    { hira: "かいしゃ", kanji: "会社", es: "empresa" },
    { hira: "しょくどう", kanji: "食堂", es: "cafetería; comedores" },
    { hira: "デパート", kanji: "", es: "grandes almacenes" },
    { hira: "かみ", kanji: "髪", es: "pelo" },
    { hira: "くち", kanji: "口", es: "boca" },
    { hira: "め", kanji: "目", es: "ojo(s)" },
    { hira: "めがね", kanji: "眼鏡", es: "lentes; gafas" },
    { hira: "うた", kanji: "歌", es: "canción" },
    { hira: "クラブ", kanji: "", es: "actividad del club" },
    { hira: "くるま", kanji: "車", es: "auto; coche; carro" },
    { hira: "ながい", kanji: "長い", es: "largo" },
    { hira: "みじかい", kanji: "短い", es: "corto (longitud)" },
    { hira: "はやい", kanji: "速い", es: "rápido" },
    { hira: "せがたかい", kanji: "背が高い", es: "alto (estatura)" },
    { hira: "せがひくい", kanji: "背が低い", es: "bajo (estatura)" },
    { hira: "あたまがいい", kanji: "頭がいい", es: "brillante; inteligente; astuto" },
    { hira: "かわいい", kanji: "", es: "lindo; tierno" },
    { hira: "しんせつ（な）", kanji: "親切（な）", es: "amable" },
    { hira: "べんり（な）", kanji: "便利（な）", es: "práctico" },
    { hira: "うたう", kanji: "歌う", es: "cantar (～を)" },
    { hira: "かぶる", kanji: "", es: "ponerse (un sombrero) (～を)" },
    { hira: "はく", kanji: "", es: "ponerse; llevar; usar (prendas bajo la cintura) (～を)" },
    { hira: "しる", kanji: "知る", es: "conocer (～を)" },
    { hira: "しっています", kanji: "知っています", es: "lo sé" },
    { hira: "しりません", kanji: "知りません", es: "no lo sé" },
    { hira: "すむ", kanji: "住む", es: "vivir en (lugar に)" },
    { hira: "はたらく", kanji: "働く", es: "trabajar" },
    { hira: "ふとる", kanji: "太る", es: "ganar peso" },
    { hira: "ふとっています", kanji: "太っています", es: "estar algo pasado de peso" },
    { hira: "かける", kanji: "", es: "ponerse (lentes/gafas)" },
    { hira: "きる", kanji: "着る", es: "ponerse; llevar; usar (prendas de cintura hacia arriba) (～を)" },
    { hira: "やせる", kanji: "", es: "perder peso" },
    { hira: "やせています", kanji: "", es: "ser delgado" },
    { hira: "けっこんする", kanji: "結婚する", es: "casarse (～と)" },
    { hira: "でも", kanji: "", es: "pero" },
    { hira: "なにも", kanji: "何も", es: "+ negativo: no… nada" },
    { hira: "…にん", kanji: "…人", es: "[contador de personas]" },
    { hira: "ひとり", kanji: "一人", es: "una persona" },
    { hira: "ふたり", kanji: "二人", es: "dos personas" },
    { hira: "べつに", kanji: "別に", es: "+ negativo: nada en especial" },
    { hira: "もちろん", kanji: "", es: "por supuesto" },
    { hira: "よかったら", kanji: "", es: "si quieres" },
  ],
  8: [
    { hira: "はれ", kanji: "晴れ", es: "soleado" },
    { hira: "あめ", kanji: "雨", es: "lluvia" },
    { hira: "くもり", kanji: "曇り", es: "nublado" },
    { hira: "ゆき", kanji: "雪", es: "nieve" },
    { hira: "てんきよほう", kanji: "天気予報", es: "pronóstico del tiempo" },
    { hira: "きおん", kanji: "気温", es: "temperatura (clima)" },
    { hira: "なつ", kanji: "夏", es: "verano" },
    { hira: "ふゆ", kanji: "冬", es: "invierno" },
    { hira: "けさ", kanji: "今朝", es: "esta mañana" },
    { hira: "あさって", kanji: "", es: "pasado mañana" },
    { hira: "まいしゅう", kanji: "每週", es: "todas las semanas" },
    { hira: "こんげつ", kanji: "今月", es: "este mes" },
    { hira: "らいげつ", kanji: "来月", es: "el próximo mes" },
    { hira: "かいしゃいん", kanji: "会社員", es: "oficinista" },
    { hira: "しごと", kanji: "仕事", es: "trabajo; ocupación" },
    { hira: "カメラ", kanji: "", es: "cámara" },
    { hira: "カラオケ", kanji: "", es: "karaoke" },
    { hira: "ところ", kanji: "所", es: "lugar" },
    { hira: "トマト", kanji: "", es: "tomate" },
    { hira: "はし", kanji: "", es: "palillos" },
    { hira: "パーティー", kanji: "", es: "fiesta" },
    { hira: "バーベキュー", kanji: "", es: "barbacoa" },
    { hira: "ホームステイ", kanji: "", es: "estancia con una familia anfitriona" },
    { hira: "おふろ", kanji: "お風呂", es: "baño" },
    { hira: "スペイン", kanji: "", es: "España" },
    { hira: "なにか", kanji: "何か", es: "algo" },
    { hira: "じょうず(な)", kanji: "上手", es: "hábil; bueno en..." },
    { hira: "へた(な)", kanji: "下手", es: "torpe; malo en..." },
    { hira: "ゆうめい(な)", kanji: "有名", es: "famoso" },
    { hira: "あらう", kanji: "洗う", es: "lavar" },
    { hira: "いう", kanji: "言う", es: "decir" },
    { hira: "おそくなる", kanji: "遅くなる", es: "llegar tarde" },
    { hira: "おもう", kanji: "思う", es: "pensar" },
    { hira: "きる", kanji: "切る", es: "cortar" },
    { hira: "つくる", kanji: "作る", es: "hacer; producir" },
    { hira: "もっていく", kanji: "持っていく", es: "llevar (algo)" },
    { hira: "じろじろみる", kanji: "じろじろ見る", es: "mirar fijamente" },
    { hira: "すてる", kanji: "捨てる", es: "tirar; desechar" },
    { hira: "はじめる", kanji: "始める", es: "empezar" },
    { hira: "うんてんする", kanji: "運転する", es: "conducir" },
    { hira: "せんたくする", kanji: "洗濯する", es: "lavar la ropa" },
    { hira: "そうじする", kanji: "掃除する", es: "limpiar" },
    { hira: "りょうりする", kanji: "料理する", es: "cocinar" },
    { hira: "～まで", kanji: "", es: "hasta..." },
    { hira: "～ぐらい", kanji: "", es: "aproximadamente..." },
    { hira: "ごめんなさい", kanji: "", es: "lo siento" },
    { hira: "だから", kanji: "", es: "por eso; por lo tanto" },
    { hira: "たくさん", kanji: "", es: "mucho" },
    { hira: "～てから", kanji: "", es: "después de..." },
    { hira: "～てもいいです", kanji: "", es: "está bien..." },
    { hira: "どうして", kanji: "", es: "por qué" },
    { hira: "ゆっくり", kanji: "", es: "despacio; con calma" },
  ],
  9: [
    { hira: "たんご", kanji: "単語", es: "palabra; vocabulario" },
    { hira: "さくぶん", kanji: "作文", es: "ensayo; composición" },
    { hira: "しけん", kanji: "試験", es: "examen" },
    { hira: "てがみ", kanji: "手紙", es: "carta" },
    { hira: "メール", kanji: "", es: "correo electrónico" },
    { hira: "ギター", kanji: "", es: "guitarra" },
    { hira: "ピアノ", kanji: "", es: "piano" },
    { hira: "コンサート", kanji: "", es: "concierto" },
    { hira: "チケット", kanji: "", es: "boleto" },
    { hira: "かぶき", kanji: "歌舞伎", es: "Kabuki; arte teatral tradicional japonés" },
    { hira: "スキー", kanji: "", es: "esquí" },
    { hira: "おべんとう", kanji: "お弁当", es: "caja de almuerzo" },
    { hira: "ピザ", kanji: "", es: "pizza" },
    { hira: "びょうき", kanji: "病気", es: "enfermedad" },
    { hira: "くすり", kanji: "薬", es: "medicina" },
    { hira: "いいこ", kanji: "いい子", es: "niño bueno" },
    { hira: "いろ", kanji: "色", es: "color" },
    { hira: "こんど", kanji: "今度", es: "futuro cercano" },
    { hira: "せんげつ", kanji: "先月", es: "el mes pasado" },
    { hira: "きょねん", kanji: "去年", es: "el año pasado" },
    { hira: "あおい", kanji: "青い", es: "azul" },
    { hira: "あかい", kanji: "赤い", es: "rojo" },
    { hira: "くろい", kanji: "黒い", es: "negro" },
    { hira: "しろい", kanji: "白い", es: "blanco" },
    { hira: "さびしい", kanji: "寂しい", es: "solitario" },
    { hira: "わかい", kanji: "若い", es: "joven" },
    { hira: "いじわる(な)", kanji: "意地悪", es: "malicioso" },
    { hira: "おどる", kanji: "踊る", es: "bailar" },
    { hira: "おわる", kanji: "終わる", es: "(algo) termina" },
    { hira: "くすりをのむ", kanji: "薬を飲む", es: "tomar medicamentos" },
    { hira: "にんきがある", kanji: "人気がある", es: "ser popular" },
    { hira: "はじまる", kanji: "始まる", es: "(algo) comienza" },
    { hira: "ひく", kanji: "弾く", es: "tocar (un instrumento de cuerda o un piano)" },
    { hira: "もらう", kanji: "", es: "obtener (de alguien)" },
    { hira: "おぼえる", kanji: "覚える", es: "memorizar" },
    { hira: "でる", kanji: "出る", es: "(1) aparecer; asistir; (2) salir" },
    { hira: "うんどうする", kanji: "運動する", es: "entrenar" },
    { hira: "さんぽする", kanji: "散歩する", es: "dar un paseo" },
    { hira: "そう", kanji: "", es: "(creo que) sí" },
    { hira: "～から", kanji: "", es: "desde ..." },
    { hira: "～まで", kanji: "", es: "hasta (lugar/tiempo)" },
    { hira: "ぜひ", kanji: "是非", es: "a toda costa; sin falta" },
    { hira: "ところで", kanji: "", es: "por cierto; a propósito" },
    { hira: "みんな", kanji: "", es: "todos" },
    { hira: "もう", kanji: "", es: "ya" },
    { hira: "ひとつ", kanji: "一つ", es: "uno" },
    { hira: "ふたつ", kanji: "二つ", es: "dos" },
    { hira: "みっつ", kanji: "三つ", es: "tres" },
    { hira: "よっつ", kanji: "四つ", es: "cuatro" },
    { hira: "いつつ", kanji: "五つ", es: "cinco" },
    { hira: "むっつ", kanji: "六つ", es: "seis" },
    { hira: "ななつ", kanji: "七つ", es: "siete" },
    { hira: "やっつ", kanji: "八つ", es: "ocho" },
    { hira: "ここのつ", kanji: "九つ", es: "nueve" },
    { hira: "とお", kanji: "", es: "diez" },
  ],
  10: [
    { hira: "きせつ", kanji: "季節", es: "estación" },
    { hira: "はる", kanji: "春", es: "primavera" },
    { hira: "あき", kanji: "秋", es: "otoño" },
    { hira: "ぎゅうにゅう", kanji: "牛乳", es: "leche" },
    { hira: "ケーキ", kanji: "", es: "pastel" },
    { hira: "すし", kanji: "", es: "sushi" },
    { hira: "てんぷら", kanji: "天ぷら", es: "tempura" },
    { hira: "りんご", kanji: "", es: "manzana" },
    { hira: "りょうり", kanji: "料理", es: "cocina (método); comida" },
    { hira: "サッカー", kanji: "", es: "fútbol" },
    { hira: "やきゅう", kanji: "野球", es: "béisbol" },
    { hira: "いしゃ", kanji: "医者", es: "doctor/ra" },
    { hira: "おかねもち", kanji: "お金持ち", es: "persona rica; millonaria" },
    { hira: "ゆうめいじん", kanji: "有名人", es: "famoso (persona)" },
    { hira: "かお", kanji: "顏", es: "cara" },
    { hira: "としうえ", kanji: "年上", es: "alguien mayor" },
    { hira: "えき", kanji: "駅", es: "estación (de trenes)" },
    { hira: "しんかんせん", kanji: "新幹線", es: "Shinkansen; \"tren bala\"" },
    { hira: "ちかてつ", kanji: "地下鉄", es: "metro" },
    { hira: "ふね", kanji: "船", es: "buque; barco" },
    { hira: "ひこうき", kanji: "飛行機", es: "avión" },
    { hira: "よやく", kanji: "予約", es: "reserva" },
    { hira: "ツアー", kanji: "", es: "tour" },
    { hira: "どうぶつえん", kanji: "動物園", es: "zoológico" },
    { hira: "じかん", kanji: "時間", es: "tiempo" },
    { hira: "せかい", kanji: "世界", es: "mundo" },
    { hira: "びよういん", kanji: "美容院", es: "salón de belleza" },
    { hira: "てぶくろ", kanji: "手袋", es: "guantes" },
    { hira: "せいかつ", kanji: "生活", es: "vida; vivir" },
    { hira: "ことし", kanji: "今年", es: "este año" },
    { hira: "あたたかい", kanji: "暖かい", es: "cálido; tibio" },
    { hira: "すずしい", kanji: "涼しい", es: "fresco (tiempo)" },
    { hira: "つめたい", kanji: "冷たい", es: "frío (cosas/personas)" },
    { hira: "おそい", kanji: "遅い", es: "lento; tarde" },
    { hira: "ねむい", kanji: "眠い", es: "somnolento" },
    { hira: "かかる", kanji: "掛かる", es: "tardar (tiempo/dinero)" },
    { hira: "とまる", kanji: "泊まる", es: "alojarse en" },
    { hira: "なる", kanji: "", es: "llegar a ser" },
    { hira: "はらう", kanji: "払う", es: "pagar" },
    { hira: "きめる", kanji: "決める", es: "decidir" },
    { hira: "りょこうする", kanji: "旅行する", es: "viajar" },
    { hira: "よやくする", kanji: "予約する", es: "reservar" },
    { hira: "どこかへ", kanji: "", es: "a algún lugar" },
    { hira: "～のほうが", kanji: "", es: "...es más..." },
    { hira: "～の中で...が一番", kanji: "", es: "entre..., ...es el más..." },
    { hira: "はやく", kanji: "早く/速く", es: "temprano; rápido" },
  ],
  11: [
    { hira: "がいこく", kanji: "外国", es: "país extranjero" },
    { hira: "オーストラリア", kanji: "", es: "Australia" },
    { hira: "かわ", kanji: "川", es: "río" },
    { hira: "おんせん", kanji: "温泉", es: "spa; aguas termales" },
    { hira: "つり", kanji: "", es: "pesca" },
    { hira: "みずうみ", kanji: "湖", es: "lago" },
    { hira: "やま", kanji: "山", es: "montaña" },
    { hira: "キャンプ", kanji: "", es: "campamento" },
    { hira: "ドライブ", kanji: "", es: "paseo (en coche)" },
    { hira: "じんじゃ", kanji: "神社", es: "santuario" },
    { hira: "びじゅつかん", kanji: "美術館", es: "museo de arte" },
    { hira: "しゃちょう", kanji: "社長", es: "presidente de una empresa" },
    { hira: "かしゅ", kanji: "歌手", es: "cantante" },
    { hira: "ルームメイト", kanji: "", es: "compañero de cuarto" },
    { hira: "ホストファミリー", kanji: "", es: "familia anfitriona" },
    { hira: "しょうらい", kanji: "将来", es: "futuro" },
    { hira: "ゆめ", kanji: "夢", es: "sueño" },
    { hira: "おまつり", kanji: "お祭り", es: "festival" },
    { hira: "おしょうがつ", kanji: "お正月", es: "Año Nuevo" },
    { hira: "おかし", kanji: "お菓子", es: "aperitivo; golosinas" },
    { hira: "ビール", kanji: "", es: "cerveza" },
    { hira: "おもちゃ", kanji: "", es: "juguete" },
    { hira: "こんがっき", kanji: "今学期", es: "este semestre" },
    { hira: "らいがっき", kanji: "来学期", es: "el próximo semestre" },
    { hira: "じゅぎょう", kanji: "授業", es: "clase" },
    { hira: "こちら", kanji: "", es: "esta persona (cortés)" },
    { hira: "うそをつく", kanji: "", es: "decir una mentira" },
    { hira: "おなかがすく", kanji: "", es: "tener hambre" },
    { hira: "かう", kanji: "飼う", es: "tener (una mascota)" },
    { hira: "サボる", kanji: "", es: "faltar a clases (sin permiso)" },
    { hira: "とる", kanji: "取る", es: "tomar (una clase); obtener (una nota)" },
    { hira: "ならう", kanji: "習う", es: "aprender" },
    { hira: "のぼる", kanji: "登る", es: "escalar" },
    { hira: "はしる", kanji: "走る", es: "correr" },
    { hira: "つかれる", kanji: "疲れる", es: "cansarse" },
    { hira: "やめる", kanji: "", es: "dejar; abandonar" },
    { hira: "けんかする", kanji: "", es: "pelear" },
    { hira: "しょうかいする", kanji: "紹介する", es: "presentar" },
    { hira: "ダイエットする", kanji: "", es: "ponerse a dieta" },
    { hira: "ちこくする", kanji: "遅刻する", es: "llegar tarde" },
    { hira: "りゅうがくする", kanji: "留学する", es: "estudiar en el extranjero" },
    { hira: "あと", kanji: "", es: "después; más tarde" },
    { hira: "～ぐらい", kanji: "", es: "aproximadamente..." },
    { hira: "ごめん", kanji: "", es: "perdón (informal)" },
    { hira: "せっかく", kanji: "", es: "con mucho esfuerzo; especialmente" },
    { hira: "～だけ", kanji: "", es: "solo..." },
    { hira: "まだ", kanji: "", es: "todavía; aún no" },
    { hira: "～までに", kanji: "", es: "para (un tiempo determinado)" },
  ],
  12: [
    { hira: "おなか", kanji: "", es: "estómago" },
    { hira: "あし", kanji: "足", es: "pierna; pie" },
    { hira: "のど", kanji: "喉", es: "garganta" },
    { hira: "は", kanji: "歯", es: "dientes" },
    { hira: "インフルエンザ", kanji: "", es: "gripe" },
    { hira: "かぜ", kanji: "風邪", es: "resfriado" },
    { hira: "せき", kanji: "", es: "tos" },
    { hira: "ふつかよい", kanji: "二日酔い", es: "resaca" },
    { hira: "ホームシック", kanji: "", es: "morriña; nostalgia" },
    { hira: "アレルギー", kanji: "", es: "alergia" },
    { hira: "ジュース", kanji: "", es: "jugo; zumo" },
    { hira: "たまご", kanji: "卵", es: "huevo" },
    { hira: "ふく", kanji: "服", es: "ropa" },
    { hira: "もの", kanji: "物", es: "cosa (objeto concreto)" },
    { hira: "プレゼント", kanji: "", es: "regalo" },
    { hira: "きっぷ", kanji: "切符", es: "ticket (de tren)" },
    { hira: "～だい", kanji: "～代", es: "tarifa; tasa" },
    { hira: "ようじ", kanji: "用事", es: "asuntos de los que ocuparse" },
    { hira: "おてあらい", kanji: "お手洗い", es: "baño; aseo" },
    { hira: "しあい", kanji: "試合", es: "partido; juego" },
    { hira: "せいじ", kanji: "政治", es: "política" },
    { hira: "せいせき", kanji: "成績", es: "nota (examen)" },
    { hira: "かのじょ", kanji: "彼女", es: "ella; novia" },
    { hira: "かれ", kanji: "彼", es: "él; novio" },
    { hira: "かれし", kanji: "彼氏", es: "novio" },
    { hira: "いみ", kanji: "意味", es: "significado" },
    { hira: "せまい", kanji: "狭い", es: "estrecho; no espacioso" },
    { hira: "ひろい", kanji: "広い", es: "amplio; espacioso" },
    { hira: "わるい", kanji: "悪い", es: "malo" },
    { hira: "いたい", kanji: "痛い", es: "dolor; doloroso" },
    { hira: "あまい", kanji: "甘い", es: "dulce" },
    { hira: "おおい", kanji: "多い", es: "haber muchos ..." },
    { hira: "すてき(な)", kanji: "素敵", es: "bonito" },
    { hira: "あるく", kanji: "歩く", es: "caminar" },
    { hira: "かぜをひく", kanji: "風邪をひく", es: "resfriarse" },
    { hira: "きょうみがある", kanji: "興味がある", es: "tener interés" },
    { hira: "なくす", kanji: "", es: "perder algo" },
    { hira: "ねつがある", kanji: "熱がある", es: "tener fiebre" },
    { hira: "のどがかわく", kanji: "喉が渇く", es: "tener sed" },
    { hira: "せきがでる", kanji: "咳が出る", es: "tener tos" },
    { hira: "わかれる", kanji: "別れる", es: "separarse; romper" },
    { hira: "きんちょうする", kanji: "緊張する", es: "ponerse nervioso" },
    { hira: "しんぱいする", kanji: "心配する", es: "preocuparse" },
    { hira: "おだいじに", kanji: "", es: "cuídate (para alguien enfermo)" },
    { hira: "～かどうか", kanji: "", es: "si... o no" },
    { hira: "～ことがあります", kanji: "", es: "haber tenido la experiencia de..." },
    { hira: "～し", kanji: "", es: "...y... (además)" },
    { hira: "～すぎます", kanji: "", es: "ser demasiado..." },
    { hira: "～たほうがいいです", kanji: "", es: "sería mejor que..." },
    { hira: "たぶん", kanji: "多分", es: "probablemente" },
    { hira: "～でしょう", kanji: "", es: "probablemente; ¿verdad?" },
    { hira: "～ので", kanji: "", es: "porque..." },
    { hira: "はじめて", kanji: "初めて", es: "por primera vez" },
    { hira: "もうすぐ", kanji: "", es: "pronto; dentro de poco" },
  ],
};
