export type GenkiVocabItem = { hira: string; kanji: string; es: string };

export const GENKI_VOCAB_BY_LESSON: Record<number, GenkiVocabItem[]> = {
  1: [
    { hira: "だいがく", kanji: "大学", es: "universidad; instituto" },
    { hira: "こうこう", kanji: "高校", es: "escuela secundaria superior" },
    { hira: "がくせい", kanji: "学生", es: "estudiante" },
    { hira: "だいがくせい", kanji: "大学生", es: "estudiante universitario" },
    { hira: "りゅうがくせい", kanji: "留学生", es: "estudiante extranjero/a" },
    { hira: "せんせい", kanji: "先生", es: "profesor/a" },
    { hira: "…ねんせい", kanji: "…年生", es: "estudiante de … año" },
    { hira: "いちねんせい", kanji: "一年生", es: "estudiante de primer año" },
    { hira: "せんこう", kanji: "専攻", es: "especialidad" },
    { hira: "わたし", kanji: "私", es: "yo" },
    { hira: "ともだち", kanji: "友だち", es: "amigo/a" },
    { hira: "…さん", kanji: "", es: "Sr./Sra. …" },
    { hira: "…じん", kanji: "…人", es: "persona de … [como gentilicio]" },
    { hira: "にほんじん", kanji: "日本人", es: "los japoneses" },
    { hira: "いま", kanji: "今", es: "ahora" },
    { hira: "ごぜん", kanji: "午前", es: "A.M." },
    { hira: "ごご", kanji: "午後", es: "P.M." },
    { hira: "…じ", kanji: "…時", es: "… en punto" },
    { hira: "いちじ", kanji: "一時", es: "la una" },
    { hira: "はん", kanji: "半", es: "y media" },
    { hira: "にじはん", kanji: "二時半", es: "las dos y media" },
    { hira: "にほん", kanji: "日本", es: "Japón" },
    { hira: "アメリカ", kanji: "", es: "EE.UU." },
    { hira: "…ご", kanji: "…語", es: "idioma …" },
    { hira: "にほんご", kanji: "日本語", es: "idioma japonés" },
    { hira: "…さい", kanji: "…歳", es: "… años de edad" },
    { hira: "でんわ", kanji: "電話", es: "teléfono" },
    { hira: "…ばん", kanji: "…番", es: "número …" },
    { hira: "ばんごう", kanji: "番号", es: "número" },
    { hira: "なまえ", kanji: "名前", es: "nombre" },
    { hira: "なん/なに", kanji: "何", es: "qué" },
    { hira: "あのう", kanji: "", es: "um…" },
    { hira: "はい", kanji: "", es: "sí" },
    { hira: "そうです", kanji: "", es: "Así es." },
    { hira: "そうですか", kanji: "", es: "Ya veo.; ¿Es así?" },
    { hira: "イギリス", kanji: "", es: "Gran Bretaña" },
    { hira: "オーストラリア", kanji: "", es: "Australia" },
    { hira: "かんこく", kanji: "韓国", es: "Corea (del Sur)" },
    { hira: "カナダ", kanji: "", es: "Canadá" },
    { hira: "ちゅうごく", kanji: "中国", es: "China" },
    { hira: "インド", kanji: "", es: "la India" },
    { hira: "エジプト", kanji: "", es: "Egipto" },
    { hira: "フィリピン", kanji: "", es: "Filipinas" },
    { hira: "アジアけんきゅう", kanji: "アジア研究", es: "estudios asiáticos" },
    { hira: "けいざい", kanji: "経済", es: "economía" },
    { hira: "こうがく", kanji: "工学", es: "ingeniería" },
    { hira: "こくさいかんけい", kanji: "国際関係", es: "relaciones internacionales" },
    { hira: "コンピューター", kanji: "", es: "informática" },
    { hira: "せいじ", kanji: "政治", es: "política" },
    { hira: "せいぶつがく", kanji: "生物学", es: "biología" },
    { hira: "ビジネス", kanji: "", es: "negocios" },
    { hira: "ぶんがく", kanji: "文学", es: "literatura" },
    { hira: "れきし", kanji: "歴史", es: "historia" },
    { hira: "いしゃ", kanji: "医者", es: "doctor/a" },
    { hira: "かいしゃいん", kanji: "会社員", es: "oficinista" },
    { hira: "かんごし", kanji: "看護師", es: "enfermero/a" },
    { hira: "こうこうせい", kanji: "高校生", es: "estudiante de secundaria superior" },
    { hira: "しゅふ", kanji: "主婦", es: "ama de casa" },
    { hira: "だいがくいんせい", kanji: "大学院生", es: "estudiante de posgrado" },
    { hira: "べんごし", kanji: "弁護士", es: "abogado/a" },
    { hira: "おかあさん", kanji: "お母さん", es: "madre" },
    { hira: "おとうさん", kanji: "お父さん", es: "padre" },
    { hira: "おねえさん", kanji: "お姉さん", es: "hermana mayor" },
    { hira: "おにいさん", kanji: "お兄さん", es: "hermano mayor" },
    { hira: "いもうと", kanji: "妹", es: "hermana menor" },
    { hira: "おとうと", kanji: "弟", es: "hermano menor" },
  ],
  2: [
    { hira: "これ", kanji: "", es: "este" },
    { hira: "それ", kanji: "", es: "ese" },
    { hira: "あれ", kanji: "", es: "aquel (el de allí)" },
    { hira: "どれ", kanji: "", es: "cuál" },
    { hira: "この", kanji: "", es: "este …" },
    { hira: "その", kanji: "", es: "ese …" },
    { hira: "あの", kanji: "", es: "aquel … (de allí)" },
    { hira: "どの", kanji: "", es: "cuál …" },
    { hira: "ここ", kanji: "", es: "aquí" },
    { hira: "そこ", kanji: "", es: "ahí" },
    { hira: "あそこ", kanji: "", es: "allí" },
    { hira: "どこ", kanji: "", es: "dónde" },
    { hira: "だれ", kanji: "", es: "quién" },
    { hira: "おいしい", kanji: "", es: "delicioso" },
    { hira: "さかな", kanji: "魚", es: "pescado" },
    { hira: "とんかつ", kanji: "", es: "chuleta de cerdo" },
    { hira: "にく", kanji: "肉", es: "carne" },
    { hira: "メニュー", kanji: "", es: "menú" },
    { hira: "やさい", kanji: "野菜", es: "verdura" },
    { hira: "かさ", kanji: "傘", es: "paraguas" },
    { hira: "かばん", kanji: "", es: "bolsa; bolso" },
    { hira: "くつ", kanji: "靴", es: "zapatos" },
    { hira: "さいふ", kanji: "財布", es: "billetera" },
    { hira: "ジーンズ", kanji: "", es: "jeans; vaqueros" },
    { hira: "じてんしゃ", kanji: "自転車", es: "bicicleta" },
    { hira: "しんぶん", kanji: "新聞", es: "periódico" },
    { hira: "スマホ", kanji: "", es: "smartphone; móvil; celular" },
    { hira: "ティーシャツ", kanji: "", es: "camiseta; playera" },
    { hira: "とけい", kanji: "時計", es: "reloj" },
    { hira: "ノート", kanji: "", es: "cuaderno" },
    { hira: "ペン", kanji: "", es: "pluma; bolígrafo" },
    { hira: "ぼうし", kanji: "帽子", es: "sombrero; gorra" },
    { hira: "ほん", kanji: "本", es: "libro" },
    { hira: "ぎんこう", kanji: "銀行", es: "banco" },
    { hira: "コンビニ", kanji: "", es: "tienda de conveniencia" },
    { hira: "トイレ", kanji: "", es: "cuarto de baño; WC" },
    { hira: "としょかん", kanji: "図書館", es: "biblioteca" },
    { hira: "ゆうびんきょく", kanji: "郵便局", es: "oficina de correos" },
    { hira: "イギリス", kanji: "", es: "Gran Bretaña" },
    { hira: "かんこく", kanji: "韓国", es: "Corea (del Sur)" },
    { hira: "ちゅうごく", kanji: "中国", es: "China" },
    { hira: "えいご", kanji: "英語", es: "inglés (idioma)" },
    { hira: "けいざい", kanji: "経済", es: "economía" },
    { hira: "コンピューター", kanji: "", es: "informática" },
    { hira: "ビジネス", kanji: "", es: "negocios" },
    { hira: "れきし", kanji: "歴史", es: "historia" },
    { hira: "おかあさん", kanji: "お母さん", es: "madre" },
    { hira: "おとうさん", kanji: "お父さん", es: "padre" },
    { hira: "いくら", kanji: "", es: "cuánto" },
    { hira: "…えん", kanji: "…円", es: "… yenes" },
    { hira: "たかい", kanji: "高い", es: "caro; alto" },
    { hira: "いらっしゃいませ", kanji: "", es: "Bienvenido (a nuestra tienda)." },
    { hira: "(…を)おねがいします", kanji: "", es: "…, por favor." },
    { hira: "(…を)ください", kanji: "", es: "Por favor, deme …" },
    { hira: "じゃあ", kanji: "", es: "entonces …; si ese es el caso, …" },
    { hira: "どうぞ", kanji: "", es: "Por favor.; Aquí tiene." },
    { hira: "どうも", kanji: "", es: "Gracias." },
  ],
  3: [
    { hira: "えいが", kanji: "映画", es: "película" },
    { hira: "おんがく", kanji: "音楽", es: "música" },
    { hira: "ざっし", kanji: "雑誌", es: "revista" },
    { hira: "スポーツ", kanji: "", es: "deportes" },
    { hira: "デート", kanji: "", es: "cita (romántica)" },
    { hira: "テニス", kanji: "", es: "tenis" },
    { hira: "テレビ", kanji: "", es: "TV" },
    { hira: "アイスクリーム", kanji: "", es: "helado" },
    { hira: "ハンバーガー", kanji: "", es: "hamburguesa" },
    { hira: "おさけ", kanji: "お酒", es: "sake; bebida alcohólica" },
    { hira: "おちゃ", kanji: "お茶", es: "té verde" },
    { hira: "コーヒー", kanji: "", es: "café" },
    { hira: "みず", kanji: "水", es: "agua" },
    { hira: "あさごはん", kanji: "朝ごはん", es: "desayuno" },
    { hira: "ひるごはん", kanji: "昼ごはん", es: "almuerzo" },
    { hira: "ばんごはん", kanji: "晩ごはん", es: "cena" },
    { hira: "いえ", kanji: "家", es: "hogar; casa" },
    { hira: "うち", kanji: "家", es: "hogar; casa; mi casa" },
    { hira: "がっこう", kanji: "学校", es: "escuela" },
    { hira: "カフェ", kanji: "", es: "cafetería" },
    { hira: "あさ", kanji: "朝", es: "mañana" },
    { hira: "きょう", kanji: "今日", es: "hoy" },
    { hira: "ごぜんちゅう", kanji: "午前中", es: "por la mañana" },
    { hira: "こんばん", kanji: "今晩", es: "esta noche" },
    { hira: "まいにち", kanji: "毎日", es: "todos los días" },
    { hira: "まいばん", kanji: "毎晩", es: "todas las noches" },
    { hira: "しゅうまつ", kanji: "週末", es: "fin de semana" },
    { hira: "どようび", kanji: "土曜日", es: "sábado" },
    { hira: "にちようび", kanji: "日曜日", es: "domingo" },
    { hira: "いつ", kanji: "", es: "cuándo" },
    { hira: "ごろ", kanji: "", es: "sobre las …" },
    { hira: "いく", kanji: "行く", es: "ir (destino に/へ)" },
    { hira: "かえる", kanji: "帰る", es: "volver; regresar (destino に/へ)" },
    { hira: "きく", kanji: "聞く", es: "escuchar; oír (～を)" },
    { hira: "のむ", kanji: "飲む", es: "tomar; beber (～を)" },
    { hira: "はなす", kanji: "話す", es: "hablar; conversar (idioma を/で)" },
    { hira: "よむ", kanji: "読む", es: "leer (～を)" },
    { hira: "おきる", kanji: "起きる", es: "levantarse" },
    { hira: "たべる", kanji: "食べる", es: "comer (～を)" },
    { hira: "ねる", kanji: "寝る", es: "dormir; irse a dormir" },
    { hira: "みる", kanji: "見る", es: "ver; mirar; observar (～を)" },
    { hira: "くる", kanji: "来る", es: "venir (destino に/へ)" },
    { hira: "する", kanji: "", es: "hacer (～を)" },
    { hira: "べんきょうする", kanji: "勉強する", es: "estudiar (～を)" },
    { hira: "いい", kanji: "", es: "bueno" },
    { hira: "はやい", kanji: "早い", es: "temprano" },
    { hira: "あまり", kanji: "", es: "+ negativo: no mucho; no tanto" },
    { hira: "ぜんぜん", kanji: "全然", es: "+ negativo: no, en absoluto" },
    { hira: "たいてい", kanji: "", es: "normalmente" },
    { hira: "ちょっと", kanji: "", es: "un poco" },
    { hira: "ときどき", kanji: "時々", es: "a veces" },
    { hira: "よく", kanji: "", es: "a menudo; mucho" },
    { hira: "そうですね", kanji: "", es: "Así es.; A ver." },
    { hira: "でも", kanji: "", es: "pero" },
    { hira: "どうですか", kanji: "", es: "¿Qué tal…?; ¿Cómo es…?" },
    { hira: "ええ", kanji: "", es: "sí" },
  ],
  4: [
    { hira: "ゲーム", kanji: "", es: "juego" },
    { hira: "アルバイト", kanji: "", es: "trabajo a tiempo parcial" },
    { hira: "かいもの", kanji: "買い物", es: "compras" },
    { hira: "クラス", kanji: "", es: "clase" },
    { hira: "いぬ", kanji: "犬", es: "perro/a" },
    { hira: "ねこ", kanji: "猫", es: "gato/a" },
    { hira: "ひと", kanji: "人", es: "persona" },
    { hira: "こども", kanji: "子供", es: "niño/a" },
    { hira: "あなた", kanji: "", es: "usted" },
    { hira: "いす", kanji: "椅子", es: "silla" },
    { hira: "つくえ", kanji: "机", es: "escritorio" },
    { hira: "しゃしん", kanji: "写真", es: "imagen; fotografía" },
    { hira: "はな", kanji: "花", es: "flor" },
    { hira: "レポート", kanji: "", es: "informe" },
    { hira: "ごはん", kanji: "ご飯", es: "arroz; comida" },
    { hira: "パン", kanji: "", es: "pan" },
    { hira: "おてら", kanji: "お寺", es: "templo" },
    { hira: "こうえん", kanji: "公園", es: "parque" },
    { hira: "スーパー", kanji: "", es: "supermercado" },
    { hira: "バスてい", kanji: "バス停", es: "parada de autobús" },
    { hira: "びょういん", kanji: "病院", es: "hospital" },
    { hira: "ホテル", kanji: "", es: "hotel" },
    { hira: "ほんや", kanji: "本屋", es: "librería" },
    { hira: "まち", kanji: "町", es: "pueblo; ciudad" },
    { hira: "レストラン", kanji: "", es: "restaurante" },
    { hira: "きのう", kanji: "昨日", es: "ayer" },
    { hira: "…じかん", kanji: "…時間", es: "… horas" },
    { hira: "いちじかん", kanji: "一時間", es: "una hora" },
    { hira: "せんしゅう", kanji: "先週", es: "la semana pasada" },
    { hira: "とき", kanji: "時", es: "cuando …; durante …" },
    { hira: "げつようび", kanji: "月曜日", es: "lunes" },
    { hira: "かようび", kanji: "火曜日", es: "martes" },
    { hira: "すいようび", kanji: "水曜日", es: "miércoles" },
    { hira: "もくようび", kanji: "木曜日", es: "jueves" },
    { hira: "きんようび", kanji: "金曜日", es: "viernes" },
    { hira: "あう", kanji: "会う", es: "conocer; ver (a una persona) (persona に)" },
    { hira: "ある", kanji: "", es: "hay… (lugar に cosa が)" },
    { hira: "かう", kanji: "買う", es: "comprar (～を)" },
    { hira: "かく", kanji: "書く", es: "escribir (persona に cosa を)" },
    { hira: "とる", kanji: "撮る", es: "tomar (una foto) (～を)" },
    { hira: "まつ", kanji: "待つ", es: "esperar (～を)" },
    { hira: "わかる", kanji: "分かる", es: "entender (～が)" },
    { hira: "いる", kanji: "", es: "(una persona) está en …; se queda en … (lugar に persona が)" },
    { hira: "ぐらい", kanji: "", es: "alrededor de (medida aproximada)" },
    { hira: "ごめんなさい", kanji: "", es: "Lo siento.; Perdón." },
    { hira: "それから", kanji: "", es: "y luego" },
    { hira: "だから", kanji: "", es: "así que; por lo tanto" },
    { hira: "たくさん", kanji: "", es: "muchos; mucho" },
    { hira: "と", kanji: "", es: "junto con (una persona); y" },
    { hira: "どうして", kanji: "", es: "por qué" },
    { hira: "ひとりで", kanji: "一人で", es: "solo" },
    { hira: "もしもし", kanji: "", es: "¿Aló?; ¿Bueno? (contestando el teléfono)" },
    { hira: "みぎ", kanji: "右", es: "derecha (～の)" },
    { hira: "ひだり", kanji: "左", es: "izquierda (～の)" },
    { hira: "まえ", kanji: "前", es: "delante de (～の)" },
    { hira: "うしろ", kanji: "後ろ", es: "atrás (～の)" },
    { hira: "なか", kanji: "中", es: "adentro (～の)" },
    { hira: "うえ", kanji: "上", es: "sobre (～の)" },
    { hira: "した", kanji: "下", es: "bajo (～の)" },
    { hira: "ちかく", kanji: "近く", es: "cerca; cercano (～の)" },
    { hira: "となり", kanji: "隣", es: "siguiente (～の)" },
    { hira: "あいだ", kanji: "間", es: "entre (AとBの)" },
  ],
  5: [
    { hira: "たべもの", kanji: "食べ物", es: "comida" },
    { hira: "のみもの", kanji: "飲み物", es: "bebida" },
    { hira: "くだもの", kanji: "果物", es: "fruta" },
    { hira: "やすみ", kanji: "休み", es: "vacaciones; día libre; ausencia" },
    { hira: "りょこう", kanji: "旅行", es: "viaje" },
    { hira: "うみ", kanji: "海", es: "mar" },
    { hira: "サーフィン", kanji: "", es: "surf" },
    { hira: "おみやげ", kanji: "お土産", es: "recuerdo; souvenir" },
    { hira: "バス", kanji: "", es: "autobús" },
    { hira: "てんき", kanji: "天気", es: "tiempo (atmosférico)" },
    { hira: "しゅくだい", kanji: "宿題", es: "deberes; tareas" },
    { hira: "テスト", kanji: "", es: "examen" },
    { hira: "たんじょうび", kanji: "誕生日", es: "cumpleaños" },
    { hira: "へや", kanji: "部屋", es: "habitación" },
    { hira: "ぼく", kanji: "僕", es: "yo (utilizado por los hombres)" },
    { hira: "エル", kanji: "Ｌ", es: "talla L" },
    { hira: "あたらしい", kanji: "新しい", es: "nuevo" },
    { hira: "ふるい", kanji: "古い", es: "viejo (cosa, no se usa para personas)" },
    { hira: "あつい", kanji: "暑い", es: "caluroso (tiempo)" },
    { hira: "さむい", kanji: "寒い", es: "frío (tiempo, no cosas)" },
    { hira: "あつい", kanji: "熱い", es: "caliente (cosa)" },
    { hira: "いそがしい", kanji: "忙しい", es: "ocupado (personas/días)" },
    { hira: "おおきい", kanji: "大きい", es: "grande" },
    { hira: "ちいさい", kanji: "小さい", es: "pequeño" },
    { hira: "おもしろい", kanji: "面白い", es: "interesante; divertido" },
    { hira: "つまらない", kanji: "", es: "aburrido" },
    { hira: "やさしい", kanji: "優しい", es: "fácil (problema); amable (persona)" },
    { hira: "むずかしい", kanji: "難しい", es: "difícil" },
    { hira: "かっこいい", kanji: "", es: "guapo (se conjuga como いい)" },
    { hira: "こわい", kanji: "怖い", es: "espeluznante; que da miedo" },
    { hira: "たのしい", kanji: "楽しい", es: "divertido" },
    { hira: "やすい", kanji: "安い", es: "económico; barato (cosa)" },
    { hira: "すき（な）", kanji: "好き（な）", es: "gustar (～が)" },
    { hira: "きらい（な）", kanji: "嫌い（な）", es: "no gustar; disgustar (～が)" },
    { hira: "だいすき（な）", kanji: "大好き（な）", es: "gustar mucho (～が)" },
    { hira: "だいきらい（な）", kanji: "大嫌い（な）", es: "odiar (～が)" },
    { hira: "きれい（な）", kanji: "", es: "bonito; limpio" },
    { hira: "げんき（な）", kanji: "元気（な）", es: "saludable; enérgico" },
    { hira: "しずか（な）", kanji: "静か（な）", es: "tranquilo" },
    { hira: "にぎやか（な）", kanji: "", es: "animado" },
    { hira: "ひま（な）", kanji: "暇（な）", es: "desocupado; libre (tiempo)" },
    { hira: "およぐ", kanji: "泳ぐ", es: "nadar" },
    { hira: "きく", kanji: "聞く", es: "preguntar (persona に)" },
    { hira: "のる", kanji: "乗る", es: "montar; abordar (～に)" },
    { hira: "やる", kanji: "", es: "hacer; realizar (～を)" },
    { hira: "でかける", kanji: "出かける", es: "salir (a comer, al cine)" },
    { hira: "いっしょに", kanji: "一緒に", es: "juntos" },
    { hira: "すごく", kanji: "", es: "extremadamente" },
    { hira: "だいじょうぶ", kanji: "大丈夫", es: "Está bien.; No hay que preocuparse." },
    { hira: "とても", kanji: "", es: "muy" },
    { hira: "どんな", kanji: "", es: "qué tipo de…" },
    { hira: "…まい", kanji: "…枚", es: "[contador de objetos planos]" },
  ],
  6: [
    { hira: "かんじ", kanji: "漢字", es: "kanji; caracter chino" },
    { hira: "きょうかしょ", kanji: "教科書", es: "libro de texto" },
    { hira: "ページ", kanji: "", es: "página" },
    { hira: "つぎ", kanji: "次", es: "siguiente" },
    { hira: "おかね", kanji: "お金", es: "dinero" },
    { hira: "にもつ", kanji: "荷物", es: "equipaje" },
    { hira: "パソコン", kanji: "", es: "computadora personal" },
    { hira: "シャワー", kanji: "", es: "ducha" },
    { hira: "エアコン", kanji: "", es: "aire acondicionado" },
    { hira: "でんき", kanji: "電気", es: "electricidad; luz" },
    { hira: "まど", kanji: "窓", es: "ventana" },
    { hira: "でんしゃ", kanji: "電車", es: "tren" },
    { hira: "くに", kanji: "国", es: "país; lugar de origen" },
    { hira: "こんしゅう", kanji: "今週", es: "esta semana" },
    { hira: "らいしゅう", kanji: "来週", es: "la próxima semana" },
    { hira: "らいねん", kanji: "来年", es: "el próximo año" },
    { hira: "よる", kanji: "夜", es: "noche" },
    { hira: "たいへん（な）", kanji: "大変（な）", es: "difícil (situación)" },
    { hira: "あそぶ", kanji: "遊ぶ", es: "jugar; pasar un rato agradable" },
    { hira: "いそぐ", kanji: "急ぐ", es: "apresurarse" },
    { hira: "かえす", kanji: "返す", es: "devolver (persona に cosa を)" },
    { hira: "けす", kanji: "消す", es: "apagar; borrar (～を)" },
    { hira: "しぬ", kanji: "死ぬ", es: "morir" },
    { hira: "すわる", kanji: "座る", es: "sentarse (asiento に)" },
    { hira: "たつ", kanji: "立つ", es: "ponerse de pie" },
    { hira: "たばこをすう", kanji: "たばこを吸う", es: "fumar" },
    { hira: "つかう", kanji: "使う", es: "utilizar (～を)" },
    { hira: "てつだう", kanji: "手伝う", es: "ayudar (persona/tarea を)" },
    { hira: "はいる", kanji: "入る", es: "entrar (～に)" },
    { hira: "もつ", kanji: "持つ", es: "llevar; sostener (～を)" },
    { hira: "やすむ", kanji: "休む", es: "(1) faltar (a…) (～を) (2) descansar" },
    { hira: "あける", kanji: "開ける", es: "abrir (algo) (～を)" },
    { hira: "しめる", kanji: "閉める", es: "cerrar (algo) (～を)" },
    { hira: "おしえる", kanji: "教える", es: "enseñar; instruir (persona に cosa を)" },
    { hira: "わすれる", kanji: "忘れる", es: "olvidar; dejar atrás (～を)" },
    { hira: "おりる", kanji: "降りる", es: "bajarse (～を)" },
    { hira: "かりる", kanji: "借りる", es: "pedir prestado (persona に cosa を)" },
    { hira: "シャワーをあびる", kanji: "", es: "ducharse" },
    { hira: "つける", kanji: "", es: "encender (～を)" },
    { hira: "でんわをかける", kanji: "電話をかける", es: "llamar (～に)" },
    { hira: "つれてくる", kanji: "連れてくる", es: "traer (a una persona) (～を)" },
    { hira: "もってくる", kanji: "持ってくる", es: "traer (una cosa) (～を)" },
    { hira: "あとで", kanji: "後で", es: "después" },
    { hira: "すぐ", kanji: "", es: "de inmediato" },
    { hira: "ゆっくり", kanji: "", es: "despacio; con calma; sin prisas" },
    { hira: "けっこうです", kanji: "結構です", es: "Estaría bien.; No sería necesario." },
    { hira: "ほんとうですか", kanji: "本当ですか", es: "¿De verdad?" },
  ],
  7: [
    { hira: "かぞく", kanji: "家族", es: "familia" },
    { hira: "おじいさん", kanji: "", es: "abuelo; anciano" },
    { hira: "おばあさん", kanji: "", es: "abuela; anciana" },
    { hira: "おにいさん", kanji: "お兄さん", es: "hermano mayor" },
    { hira: "おねえさん", kanji: "お姉さん", es: "hermana mayor" },
    { hira: "ちち", kanji: "父", es: "(mi) padre" },
    { hira: "はは", kanji: "母", es: "(mi) madre" },
    { hira: "あに", kanji: "兄", es: "(mi) hermano mayor" },
    { hira: "あね", kanji: "姉", es: "(mi) hermana mayor" },
    { hira: "いもうと", kanji: "妹", es: "hermana menor" },
    { hira: "おとうと", kanji: "弟", es: "hermano menor" },
    { hira: "きょうだい", kanji: "兄弟", es: "hermanos y hermanas" },
    { hira: "おとこのひと", kanji: "男の人", es: "hombre" },
    { hira: "おんなのひと", kanji: "女の人", es: "mujer" },
    { hira: "かいしゃ", kanji: "会社", es: "empresa" },
    { hira: "しょくどう", kanji: "食堂", es: "cafetería; comedores" },
    { hira: "デパート", kanji: "", es: "grandes almacenes" },
    { hira: "かみ", kanji: "髪", es: "pelo" },
    { hira: "くち", kanji: "口", es: "boca" },
    { hira: "め", kanji: "目", es: "ojo(s)" },
    { hira: "めがね", kanji: "眼鏡", es: "lentes; gafas" },
    { hira: "うた", kanji: "歌", es: "canción" },
    { hira: "クラブ", kanji: "", es: "actividad del club" },
    { hira: "くるま", kanji: "車", es: "auto; coche; carro" },
    { hira: "ながい", kanji: "長い", es: "largo" },
    { hira: "みじかい", kanji: "短い", es: "corto (longitud)" },
    { hira: "はやい", kanji: "速い", es: "rápido" },
    { hira: "せがたかい", kanji: "背が高い", es: "alto (estatura)" },
    { hira: "せがひくい", kanji: "背が低い", es: "bajo (estatura)" },
    { hira: "あたまがいい", kanji: "頭がいい", es: "brillante; inteligente; astuto" },
    { hira: "かわいい", kanji: "", es: "lindo; tierno" },
    { hira: "しんせつ（な）", kanji: "親切（な）", es: "amable" },
    { hira: "べんり（な）", kanji: "便利（な）", es: "práctico" },
    { hira: "うたう", kanji: "歌う", es: "cantar (～を)" },
    { hira: "かぶる", kanji: "", es: "ponerse (un sombrero) (～を)" },
    { hira: "はく", kanji: "", es: "ponerse; llevar; usar (prendas bajo la cintura) (～を)" },
    { hira: "しる", kanji: "知る", es: "conocer (～を)" },
    { hira: "しっています", kanji: "知っています", es: "lo sé" },
    { hira: "しりません", kanji: "知りません", es: "no lo sé" },
    { hira: "すむ", kanji: "住む", es: "vivir en (lugar に)" },
    { hira: "はたらく", kanji: "働く", es: "trabajar" },
    { hira: "ふとる", kanji: "太る", es: "ganar peso" },
    { hira: "ふとっています", kanji: "太っています", es: "estar algo pasado de peso" },
    { hira: "かける", kanji: "", es: "ponerse (lentes/gafas)" },
    { hira: "きる", kanji: "着る", es: "ponerse; llevar; usar (prendas de cintura hacia arriba) (～を)" },
    { hira: "やせる", kanji: "", es: "perder peso" },
    { hira: "やせています", kanji: "", es: "ser delgado" },
    { hira: "けっこんする", kanji: "結婚する", es: "casarse (～と)" },
    { hira: "でも", kanji: "", es: "pero" },
    { hira: "なにも", kanji: "何も", es: "+ negativo: no… nada" },
    { hira: "…にん", kanji: "…人", es: "[contador de personas]" },
    { hira: "ひとり", kanji: "一人", es: "una persona" },
    { hira: "ふたり", kanji: "二人", es: "dos personas" },
    { hira: "べつに", kanji: "別に", es: "+ negativo: nada en especial" },
    { hira: "もちろん", kanji: "", es: "por supuesto" },
    { hira: "よかったら", kanji: "", es: "si quieres" },
  ],
};